// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ActivityService is the unified event feed for the app: every service
 * that wants to surface a meaningful event for the user (vault locked,
 * exec finished, plugin failed, sync pushed…) calls Record and the
 * frontend ActivityPanel renders it chronologically.
 * 
 * Recording emits a Wails event so the panel can append in realtime
 * without polling. Recording errors are swallowed — the activity feed
 * is observability, not load-bearing; if SQLite is unhappy the rest of
 * the app should keep working.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "./internal/store/models.js";

export function List(f: store$0.ActivityFilter): $CancellablePromise<store$0.Activity[]> {
    return $Call.ByID(2874726812, f).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * PurgeOlderThanDays drops rows older than the given window. Called from
 * the UI as a manual cleanup; a 30-day window covers most observability
 * needs and keeps the DB tidy.
 */
export function PurgeOlderThanDays(days: number): $CancellablePromise<number> {
    return $Call.ByID(4133030167, days);
}

/**
 * Record persists and broadcasts. Other Go services hold a *store.Activities
 * directly so they don't go through this method (it lives on the service
 * surface for Wails-bound calls), but they call ActivityService.Record
 * when they want the realtime fan-out side-effect too. To keep both paths
 * consistent there's also a free Record helper below.
 */
export function Record(a: store$0.Activity): $CancellablePromise<store$0.Activity> {
    return $Call.ByID(1202621025, a).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Sources(): $CancellablePromise<string[]> {
    return $Call.ByID(3791644422).then(($result: any) => {
        return $$createType2($result);
    });
}

// Private type creation functions
const $$createType0 = store$0.Activity.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
