// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * Explain streams an analysis of pasted output/errors/logs back to the
 * frontend via "ai:chunk" events. Returns immediately; the caller listens
 * for chunks tagged with the given streamID.
 */
export function Explain(streamID: string, content: string, kind: string): $CancellablePromise<void> {
    return $Call.ByID(2845003630, streamID, content, kind);
}

/**
 * IsConfigured is a fast pre-check the UI can use before showing AI affordances.
 */
export function IsConfigured(): $CancellablePromise<boolean> {
    return $Call.ByID(632013635);
}

/**
 * Stop terminates an in-flight Explain stream.
 */
export function Stop(streamID: string): $CancellablePromise<void> {
    return $Call.ByID(926188863, streamID);
}

/**
 * Translate maps a natural-language description to a single shell command.
 * One-shot; small token budget; no streaming since the response is tiny.
 */
export function Translate(prompt: string, shellHint: string, hostHint: string): $CancellablePromise<string> {
    return $Call.ByID(2432548167, prompt, shellHint, hostHint);
}
