// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AutoLockService watches a "last user activity" timestamp and re-locks the
 * vault after configurable idleness. The frontend pings Touch() on input.
 * 
 * 0 minutes disables auto-lock.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * Start the background ticker. Idempotent — calling twice is harmless.
 */
export function Start(): $CancellablePromise<void> {
    return $Call.ByID(123661047);
}

/**
 * Touch resets the idle timer. The frontend calls this on key/click activity.
 */
export function Touch(): $CancellablePromise<void> {
    return $Call.ByID(3902580208);
}
