// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} runID
 * @param {string} command
 * @param {string[]} hostIDs
 * @param {{ [_ in string]?: string }} passwords
 * @param {number} timeoutSeconds
 * @returns {$CancellablePromise<$models.ExecResult[]>}
 */
export function Run(runID, command, hostIDs, passwords, timeoutSeconds) {
    return $Call.ByID(3711711345, runID, command, hostIDs, passwords, timeoutSeconds).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.ExecResult.createFrom;
const $$createType1 = $Create.Array($$createType0);
