// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * HistoryService is the frontend-visible wrapper. Backend services
 * (ExecService, SnippetService) call store.History.Add directly; this is
 * the read/maintenance side.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "./internal/store/models.js";

/**
 * Add lets the frontend record a command (used when the AI drawer's "insert
 * into terminal" is clicked, for example).
 */
export function Add(e: store$0.HistoryEntry): $CancellablePromise<store$0.HistoryEntry> {
    return $Call.ByID(3425385348, e).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Clear(): $CancellablePromise<void> {
    return $Call.ByID(2353432274);
}

export function Delete(id: string): $CancellablePromise<void> {
    return $Call.ByID(3921506394, id);
}

export function List(hostID: string, source: string, limit: number): $CancellablePromise<store$0.HistoryEntry[]> {
    return $Call.ByID(671552305, hostID, source, limit).then(($result: any) => {
        return $$createType1($result);
    });
}

export function Search(query: string): $CancellablePromise<store$0.HistoryEntry[]> {
    return $Call.ByID(1691045273, query).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = store$0.HistoryEntry.createFrom;
const $$createType1 = $Create.Array($$createType0);
