// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "./internal/store/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Create(h: store$0.Host): $CancellablePromise<store$0.Host> {
    return $Call.ByID(3307292291, h).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Delete(id: string): $CancellablePromise<void> {
    return $Call.ByID(2448941168, id);
}

export function Get(id: string): $CancellablePromise<store$0.Host> {
    return $Call.ByID(3677749373, id).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ImportSSHConfigEntries bulk-creates Host records from a user-curated
 * subset of ScanSSHConfig results. Returns the count actually inserted.
 * 
 * Auth is heuristically defaulted: if the entry has an IdentityFile, mark
 * the host as "key" auth (the user must still link a vault key after
 * import); otherwise fall back to "agent" so existing ssh-agent setups work
 * out of the box.
 * 
 * ProxyJump auto-link: a second pass resolves each entry's ProxyJump alias
 * against the set of just-imported names plus any pre-existing saved host.
 * Resolved links are written to the host record; unresolved references are
 * left in the notes field so the user can fix them by hand.
 */
export function ImportSSHConfigEntries(entries: $models.SSHConfigCandidate[]): $CancellablePromise<number> {
    return $Call.ByID(1128560174, entries);
}

export function List(): $CancellablePromise<store$0.Host[]> {
    return $Call.ByID(3424268411).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ScanSSHConfig reads ~/.ssh/config (or %USERPROFILE%\.ssh\config on Windows)
 * and returns importable Host entries. Wildcard patterns (`*`, `?`, `!`) and
 * the catch-all `*` block are skipped — they're behavioral defaults, not
 * connectable hosts.
 */
export function ScanSSHConfig(): $CancellablePromise<$models.SSHConfigCandidate[]> {
    return $Call.ByID(932094358).then(($result: any) => {
        return $$createType3($result);
    });
}

export function Update(h: store$0.Host): $CancellablePromise<void> {
    return $Call.ByID(790994162, h);
}

// Private type creation functions
const $$createType0 = store$0.Host.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.SSHConfigCandidate.createFrom;
const $$createType3 = $Create.Array($$createType2);
