// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "./internal/store/models.js";

/**
 * @param {store$0.Host} h
 * @returns {$CancellablePromise<store$0.Host>}
 */
export function Create(h) {
    return $Call.ByID(3307292291, h).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function Delete(id) {
    return $Call.ByID(2448941168, id);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<store$0.Host>}
 */
export function Get(id) {
    return $Call.ByID(3677749373, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<store$0.Host[]>}
 */
export function List() {
    return $Call.ByID(3424268411).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {store$0.Host} h
 * @returns {$CancellablePromise<void>}
 */
export function Update(h) {
    return $Call.ByID(790994162, h);
}

// Private type creation functions
const $$createType0 = store$0.Host.createFrom;
const $$createType1 = $Create.Array($$createType0);
