// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "./internal/store/models.js";

export function Create(h: store$0.Host): $CancellablePromise<store$0.Host> {
    return $Call.ByID(3307292291, h).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Delete(id: string): $CancellablePromise<void> {
    return $Call.ByID(2448941168, id);
}

export function Get(id: string): $CancellablePromise<store$0.Host> {
    return $Call.ByID(3677749373, id).then(($result: any) => {
        return $$createType0($result);
    });
}

export function List(): $CancellablePromise<store$0.Host[]> {
    return $Call.ByID(3424268411).then(($result: any) => {
        return $$createType1($result);
    });
}

export function Update(h: store$0.Host): $CancellablePromise<void> {
    return $Call.ByID(790994162, h);
}

// Private type creation functions
const $$createType0 = store$0.Host.createFrom;
const $$createType1 = $Create.Array($$createType0);
