// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * HTTPService runs HTTP requests *through* a connected SSH host. The host
 * can therefore reach internal services that the local machine can't —
 * staging APIs behind a VPC bastion, a Postgres health endpoint on a
 * private subnet, etc.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Request fires a single HTTP request and returns the response. Body capped
 * at 1MB to keep the JSON bridge healthy; flagged via Truncated so the UI
 * can warn.
 * @param {string} hostID
 * @param {string} password
 * @param {$models.HTTPRequestOptions} opts
 * @returns {$CancellablePromise<$models.HTTPResponse>}
 */
export function Request(hostID, password, opts) {
    return $Call.ByID(3181893466, hostID, password, opts).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.HTTPResponse.createFrom;
