// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "./internal/store/models.js";

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteQuery(id) {
    return $Call.ByID(2861025779, id);
}

/**
 * @returns {$CancellablePromise<store$0.LogQuery[]>}
 */
export function ListQueries() {
    return $Call.ByID(4105027962).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * Saved-query CRUD lives on the same service the panel already binds to —
 * avoids spinning up a third service for two thin methods.
 * @param {store$0.LogQuery} q
 * @returns {$CancellablePromise<store$0.LogQuery>}
 */
export function SaveQuery(q) {
    return $Call.ByID(3917505437, q).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Start opens a session per host and runs `command` (e.g. `tail -F /var/log/syslog`),
 * streaming lines back as `logs:line` events. Idempotent — calling Start with
 * an existing streamID kills the old run first.
 * @param {string} streamID
 * @param {string[]} hostIDs
 * @param {{ [_ in string]?: string }} passwords
 * @param {string} command
 * @returns {$CancellablePromise<void>}
 */
export function Start(streamID, hostIDs, passwords, command) {
    return $Call.ByID(2655905362, streamID, hostIDs, passwords, command);
}

/**
 * @param {string} streamID
 * @returns {$CancellablePromise<void>}
 */
export function Stop(streamID) {
    return $Call.ByID(3761781266, streamID);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function StopAll() {
    return $Call.ByID(4263053065);
}

// Private type creation functions
const $$createType0 = store$0.LogQuery.createFrom;
const $$createType1 = $Create.Array($$createType0);
