// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as recorder$0 from "./internal/recorder/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "./internal/store/models.js";

/**
 * AIChunk is the streaming payload — the frontend appends `delta` text to the
 * currently-rendering message and uses `done` to know when to stop.
 */
export class AIChunk {
    "streamID": string;
    "delta": string;
    "done": boolean;
    "error"?: string;

    /** Creates a new AIChunk instance. */
    constructor($$source: Partial<AIChunk> = {}) {
        if (!("streamID" in $$source)) {
            this["streamID"] = "";
        }
        if (!("delta" in $$source)) {
            this["delta"] = "";
        }
        if (!("done" in $$source)) {
            this["done"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIChunk instance from a string or object.
     */
    static createFrom($$source: any = {}): AIChunk {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AIChunk($$parsedSource as Partial<AIChunk>);
    }
}

/**
 * ActiveForward bundles a saved forward with its current runtime state.
 */
export class ActiveForward {
    "id": string;
    "name": string;
    "hostID": string;
    "kind": store$0.ForwardKind;
    "localAddr": string;
    "localPort": number;
    "remoteAddr"?: string;
    "remotePort"?: number;
    "autoStart": boolean;
    "createdAt": number;
    "active": boolean;

    /** Creates a new ActiveForward instance. */
    constructor($$source: Partial<ActiveForward> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("hostID" in $$source)) {
            this["hostID"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = store$0.ForwardKind.$zero;
        }
        if (!("localAddr" in $$source)) {
            this["localAddr"] = "";
        }
        if (!("localPort" in $$source)) {
            this["localPort"] = 0;
        }
        if (!("autoStart" in $$source)) {
            this["autoStart"] = false;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = 0;
        }
        if (!("active" in $$source)) {
            this["active"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ActiveForward instance from a string or object.
     */
    static createFrom($$source: any = {}): ActiveForward {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ActiveForward($$parsedSource as Partial<ActiveForward>);
    }
}

/**
 * AppSettings is the safe shape returned to the frontend — never includes
 * raw secrets, just whether each one is set.
 */
export class AppSettings {
    "theme": string;
    "autoLockMinutes": number;
    "defaultShellPath": string;
    "metricsIntervalSeconds": number;
    "hasAnthropicKey": boolean;

    /** Creates a new AppSettings instance. */
    constructor($$source: Partial<AppSettings> = {}) {
        if (!("theme" in $$source)) {
            this["theme"] = "";
        }
        if (!("autoLockMinutes" in $$source)) {
            this["autoLockMinutes"] = 0;
        }
        if (!("defaultShellPath" in $$source)) {
            this["defaultShellPath"] = "";
        }
        if (!("metricsIntervalSeconds" in $$source)) {
            this["metricsIntervalSeconds"] = 0;
        }
        if (!("hasAnthropicKey" in $$source)) {
            this["hasAnthropicKey"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): AppSettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppSettings($$parsedSource as Partial<AppSettings>);
    }
}

/**
 * CastEvent is the over-the-wire shape of a single playback event. The cast
 * internal type uses a custom MarshalJSON for asciinema compatibility, which
 * the Wails binding generator can't introspect — this struct is the "wire"
 * view used when handing events to the frontend.
 */
export class CastEvent {
    "offset": number;
    "kind": string;
    "data": string;

    /** Creates a new CastEvent instance. */
    constructor($$source: Partial<CastEvent> = {}) {
        if (!("offset" in $$source)) {
            this["offset"] = 0;
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("data" in $$source)) {
            this["data"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CastEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): CastEvent {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CastEvent($$parsedSource as Partial<CastEvent>);
    }
}

export class CertInfo {
    "subject": string;
    "issuer": string;
    "notBefore": number;
    "notAfter": number;
    "daysUntilExpiry": number;
    "dnsNames": string[];
    "fingerprint": string;
    "serialNumber": string;

    /**
     * each peer subject, leaf-first
     */
    "chain": string[];

    /** Creates a new CertInfo instance. */
    constructor($$source: Partial<CertInfo> = {}) {
        if (!("subject" in $$source)) {
            this["subject"] = "";
        }
        if (!("issuer" in $$source)) {
            this["issuer"] = "";
        }
        if (!("notBefore" in $$source)) {
            this["notBefore"] = 0;
        }
        if (!("notAfter" in $$source)) {
            this["notAfter"] = 0;
        }
        if (!("daysUntilExpiry" in $$source)) {
            this["daysUntilExpiry"] = 0;
        }
        if (!("dnsNames" in $$source)) {
            this["dnsNames"] = [];
        }
        if (!("fingerprint" in $$source)) {
            this["fingerprint"] = "";
        }
        if (!("serialNumber" in $$source)) {
            this["serialNumber"] = "";
        }
        if (!("chain" in $$source)) {
            this["chain"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CertInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): CertInfo {
        const $$createField5_0 = $$createType0;
        const $$createField8_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("dnsNames" in $$parsedSource) {
            $$parsedSource["dnsNames"] = $$createField5_0($$parsedSource["dnsNames"]);
        }
        if ("chain" in $$parsedSource) {
            $$parsedSource["chain"] = $$createField8_0($$parsedSource["chain"]);
        }
        return new CertInfo($$parsedSource as Partial<CertInfo>);
    }
}

/**
 * Container is the wire shape returned to the frontend. We deliberately keep
 * this language-agnostic — Docker, Podman, and Kubernetes pods all map onto it.
 */
export class Container {
    "id": string;
    "name": string;
    "image": string;
    "status": string;
    "state": string;
    "ports": string;
    "created": string;

    /** Creates a new Container instance. */
    constructor($$source: Partial<Container> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("image" in $$source)) {
            this["image"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("ports" in $$source)) {
            this["ports"] = "";
        }
        if (!("created" in $$source)) {
            this["created"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Container instance from a string or object.
     */
    static createFrom($$source: any = {}): Container {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Container($$parsedSource as Partial<Container>);
    }
}

/**
 * DBColumn describes one column for the schema browser's column drawer.
 */
export class DBColumn {
    "name": string;
    "dataType": string;
    "nullable": boolean;
    "default"?: string;
    "isPrimary": boolean;
    "ordinalPos": number;

    /** Creates a new DBColumn instance. */
    constructor($$source: Partial<DBColumn> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("dataType" in $$source)) {
            this["dataType"] = "";
        }
        if (!("nullable" in $$source)) {
            this["nullable"] = false;
        }
        if (!("isPrimary" in $$source)) {
            this["isPrimary"] = false;
        }
        if (!("ordinalPos" in $$source)) {
            this["ordinalPos"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DBColumn instance from a string or object.
     */
    static createFrom($$source: any = {}): DBColumn {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DBColumn($$parsedSource as Partial<DBColumn>);
    }
}

/**
 * DBConnectionInfo is the safe view of an open connection — enough to render
 * "you're connected to X as Y" without surfacing the password back to the UI.
 */
export class DBConnectionInfo {
    "connID": string;

    /**
     * "postgres" | "mysql"
     */
    "kind": string;
    "hostID": string;
    "hostName": string;
    "database": string;
    "user": string;

    /**
     * host:port from the DSN
     */
    "server": string;

    /** Creates a new DBConnectionInfo instance. */
    constructor($$source: Partial<DBConnectionInfo> = {}) {
        if (!("connID" in $$source)) {
            this["connID"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("hostID" in $$source)) {
            this["hostID"] = "";
        }
        if (!("hostName" in $$source)) {
            this["hostName"] = "";
        }
        if (!("database" in $$source)) {
            this["database"] = "";
        }
        if (!("user" in $$source)) {
            this["user"] = "";
        }
        if (!("server" in $$source)) {
            this["server"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DBConnectionInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): DBConnectionInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DBConnectionInfo($$parsedSource as Partial<DBConnectionInfo>);
    }
}

/**
 * DBTable is one entry in the schema browser. RowEstimate is best-effort —
 * information_schema gives an estimate on Postgres (pg_class.reltuples) and
 * the storage engine's running estimate on MySQL (TABLE_ROWS), neither of
 * which is exact for active tables.
 */
export class DBTable {
    "schema": string;
    "name": string;

    /**
     * "table" | "view"
     */
    "kind": string;
    "rowEstimate": number;

    /** Creates a new DBTable instance. */
    constructor($$source: Partial<DBTable> = {}) {
        if (!("schema" in $$source)) {
            this["schema"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("rowEstimate" in $$source)) {
            this["rowEstimate"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DBTable instance from a string or object.
     */
    static createFrom($$source: any = {}): DBTable {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DBTable($$parsedSource as Partial<DBTable>);
    }
}

export class DNSAnswer {
    "type": string;
    "value": string;

    /** Creates a new DNSAnswer instance. */
    constructor($$source: Partial<DNSAnswer> = {}) {
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("value" in $$source)) {
            this["value"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DNSAnswer instance from a string or object.
     */
    static createFrom($$source: any = {}): DNSAnswer {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DNSAnswer($$parsedSource as Partial<DNSAnswer>);
    }
}

export class DNSResult {
    "target": string;
    "answers": DNSAnswer[];
    "rawOutput": string;

    /** Creates a new DNSResult instance. */
    constructor($$source: Partial<DNSResult> = {}) {
        if (!("target" in $$source)) {
            this["target"] = "";
        }
        if (!("answers" in $$source)) {
            this["answers"] = [];
        }
        if (!("rawOutput" in $$source)) {
            this["rawOutput"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DNSResult instance from a string or object.
     */
    static createFrom($$source: any = {}): DNSResult {
        const $$createField1_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("answers" in $$parsedSource) {
            $$parsedSource["answers"] = $$createField1_0($$parsedSource["answers"]);
        }
        return new DNSResult($$parsedSource as Partial<DNSResult>);
    }
}

export class ExecProgress {
    "runID": string;
    "result": ExecResult;

    /** Creates a new ExecProgress instance. */
    constructor($$source: Partial<ExecProgress> = {}) {
        if (!("runID" in $$source)) {
            this["runID"] = "";
        }
        if (!("result" in $$source)) {
            this["result"] = (new ExecResult());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExecProgress instance from a string or object.
     */
    static createFrom($$source: any = {}): ExecProgress {
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("result" in $$parsedSource) {
            $$parsedSource["result"] = $$createField1_0($$parsedSource["result"]);
        }
        return new ExecProgress($$parsedSource as Partial<ExecProgress>);
    }
}

/**
 * ExecResult is the per-host outcome of a multi-host run.
 */
export class ExecResult {
    "hostID": string;
    "hostName": string;
    "stdout": string;
    "stderr": string;
    "exitCode": number;
    "error"?: string;
    "attempts": number;
    "durationMs": number;

    /** Creates a new ExecResult instance. */
    constructor($$source: Partial<ExecResult> = {}) {
        if (!("hostID" in $$source)) {
            this["hostID"] = "";
        }
        if (!("hostName" in $$source)) {
            this["hostName"] = "";
        }
        if (!("stdout" in $$source)) {
            this["stdout"] = "";
        }
        if (!("stderr" in $$source)) {
            this["stderr"] = "";
        }
        if (!("exitCode" in $$source)) {
            this["exitCode"] = 0;
        }
        if (!("attempts" in $$source)) {
            this["attempts"] = 0;
        }
        if (!("durationMs" in $$source)) {
            this["durationMs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExecResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ExecResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ExecResult($$parsedSource as Partial<ExecResult>);
    }
}

/**
 * HTTPHeader is one response header. Flat (name, value) pairs preserve the
 * order the server sent (map iteration would lose it).
 */
export class HTTPHeader {
    "name": string;
    "value": string;

    /** Creates a new HTTPHeader instance. */
    constructor($$source: Partial<HTTPHeader> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("value" in $$source)) {
            this["value"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HTTPHeader instance from a string or object.
     */
    static createFrom($$source: any = {}): HTTPHeader {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HTTPHeader($$parsedSource as Partial<HTTPHeader>);
    }
}

/**
 * HTTPRequestOptions is the wire shape from the frontend. We accept headers
 * as a flat map of single values (the multi-value rare-case is rejected on
 * the way out — most ops debugging fits this shape and the UI is simpler).
 */
export class HTTPRequestOptions {
    "method": string;
    "url": string;
    "headers": { [_ in string]?: string };
    "body": string;

    /**
     * Skip TLS verification for the request. The SSL cert inspector and the
     * browser do this too — this is a debug tool, not a security boundary.
     */
    "insecureSkipVerify": boolean;

    /** Creates a new HTTPRequestOptions instance. */
    constructor($$source: Partial<HTTPRequestOptions> = {}) {
        if (!("method" in $$source)) {
            this["method"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("headers" in $$source)) {
            this["headers"] = {};
        }
        if (!("body" in $$source)) {
            this["body"] = "";
        }
        if (!("insecureSkipVerify" in $$source)) {
            this["insecureSkipVerify"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HTTPRequestOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): HTTPRequestOptions {
        const $$createField2_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("headers" in $$parsedSource) {
            $$parsedSource["headers"] = $$createField2_0($$parsedSource["headers"]);
        }
        return new HTTPRequestOptions($$parsedSource as Partial<HTTPRequestOptions>);
    }
}

export class HTTPResponse {
    "status": number;
    "statusText": string;
    "proto": string;
    "headers": HTTPHeader[];
    "body": string;

    /**
     * true if Body is base64 (binary response)
     */
    "bodyBase64": boolean;
    "sizeBytes": number;
    "truncated": boolean;
    "durationMs": number;

    /** Creates a new HTTPResponse instance. */
    constructor($$source: Partial<HTTPResponse> = {}) {
        if (!("status" in $$source)) {
            this["status"] = 0;
        }
        if (!("statusText" in $$source)) {
            this["statusText"] = "";
        }
        if (!("proto" in $$source)) {
            this["proto"] = "";
        }
        if (!("headers" in $$source)) {
            this["headers"] = [];
        }
        if (!("body" in $$source)) {
            this["body"] = "";
        }
        if (!("bodyBase64" in $$source)) {
            this["bodyBase64"] = false;
        }
        if (!("sizeBytes" in $$source)) {
            this["sizeBytes"] = 0;
        }
        if (!("truncated" in $$source)) {
            this["truncated"] = false;
        }
        if (!("durationMs" in $$source)) {
            this["durationMs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HTTPResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): HTTPResponse {
        const $$createField3_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("headers" in $$parsedSource) {
            $$parsedSource["headers"] = $$createField3_0($$parsedSource["headers"]);
        }
        return new HTTPResponse($$parsedSource as Partial<HTTPResponse>);
    }
}

export class HostMetrics {
    "hostID": string;
    "hostName": string;
    "online": boolean;
    "cpuPercent": number;
    "memPercent": number;
    "diskPercent": number;
    "loadAvg1": number;

    /**
     * Network throughput averaged over the interval since the previous tick.
     * Aggregated across all non-loopback interfaces. First sample after Start
     * has rates of zero (no prior to compare against).
     */
    "rxBytesPerSec": number;
    "txBytesPerSec": number;
    "rxBytesTotal": number;
    "txBytesTotal": number;
    "timestamp": number;
    "error"?: string;

    /** Creates a new HostMetrics instance. */
    constructor($$source: Partial<HostMetrics> = {}) {
        if (!("hostID" in $$source)) {
            this["hostID"] = "";
        }
        if (!("hostName" in $$source)) {
            this["hostName"] = "";
        }
        if (!("online" in $$source)) {
            this["online"] = false;
        }
        if (!("cpuPercent" in $$source)) {
            this["cpuPercent"] = 0;
        }
        if (!("memPercent" in $$source)) {
            this["memPercent"] = 0;
        }
        if (!("diskPercent" in $$source)) {
            this["diskPercent"] = 0;
        }
        if (!("loadAvg1" in $$source)) {
            this["loadAvg1"] = 0;
        }
        if (!("rxBytesPerSec" in $$source)) {
            this["rxBytesPerSec"] = 0;
        }
        if (!("txBytesPerSec" in $$source)) {
            this["txBytesPerSec"] = 0;
        }
        if (!("rxBytesTotal" in $$source)) {
            this["rxBytesTotal"] = 0;
        }
        if (!("txBytesTotal" in $$source)) {
            this["txBytesTotal"] = 0;
        }
        if (!("timestamp" in $$source)) {
            this["timestamp"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HostMetrics instance from a string or object.
     */
    static createFrom($$source: any = {}): HostMetrics {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HostMetrics($$parsedSource as Partial<HostMetrics>);
    }
}

/**
 * LogLine is the per-line payload streamed to the frontend during a log run.
 * Lines from multiple hosts share a single streamID so the UI can colocate
 * them in one view, and each line carries its hostName so the UI can colour /
 * label without a second lookup.
 */
export class LogLine {
    "streamID": string;
    "hostID": string;
    "hostName": string;
    "line": string;
    "isStderr": boolean;
    "timestamp": number;

    /** Creates a new LogLine instance. */
    constructor($$source: Partial<LogLine> = {}) {
        if (!("streamID" in $$source)) {
            this["streamID"] = "";
        }
        if (!("hostID" in $$source)) {
            this["hostID"] = "";
        }
        if (!("hostName" in $$source)) {
            this["hostName"] = "";
        }
        if (!("line" in $$source)) {
            this["line"] = "";
        }
        if (!("isStderr" in $$source)) {
            this["isStderr"] = false;
        }
        if (!("timestamp" in $$source)) {
            this["timestamp"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogLine instance from a string or object.
     */
    static createFrom($$source: any = {}): LogLine {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LogLine($$parsedSource as Partial<LogLine>);
    }
}

/**
 * Notification is the wire shape: matches what the in-app toast renders and
 * what the webhook receives.
 */
export class Notification {
    "id": string;
    "kind": NotifyKind;
    "title": string;
    "body": string;

    /**
     * "exec" | "metrics" | "test" | etc.
     */
    "source": string;
    "hostName"?: string;
    "timestamp": number;

    /** Creates a new Notification instance. */
    constructor($$source: Partial<Notification> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = NotifyKind.$zero;
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("body" in $$source)) {
            this["body"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("timestamp" in $$source)) {
            this["timestamp"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Notification instance from a string or object.
     */
    static createFrom($$source: any = {}): Notification {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Notification($$parsedSource as Partial<Notification>);
    }
}

/**
 * NotifyConfig is what we expose to the frontend Settings panel.
 */
export class NotifyConfig {
    "desktopEnabled": boolean;
    "webhookURL": string;
    "longExecSeconds": number;

    /** Creates a new NotifyConfig instance. */
    constructor($$source: Partial<NotifyConfig> = {}) {
        if (!("desktopEnabled" in $$source)) {
            this["desktopEnabled"] = false;
        }
        if (!("webhookURL" in $$source)) {
            this["webhookURL"] = "";
        }
        if (!("longExecSeconds" in $$source)) {
            this["longExecSeconds"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NotifyConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): NotifyConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NotifyConfig($$parsedSource as Partial<NotifyConfig>);
    }
}

/**
 * NotifyKind classifies the notification so the UI can pick an icon/colour.
 */
export enum NotifyKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    NotifyInfo = "info",
    NotifyOK = "ok",
    NotifyWarn = "warn",
    NotifyError = "error",
};

export class PingResult {
    "target": string;
    "reachable": boolean;
    "sent": number;
    "received": number;
    "lost": number;
    "lossPercent": number;
    "avgLatencyMs": number;
    "minLatencyMs": number;
    "maxLatencyMs": number;
    "rawOutput": string;

    /** Creates a new PingResult instance. */
    constructor($$source: Partial<PingResult> = {}) {
        if (!("target" in $$source)) {
            this["target"] = "";
        }
        if (!("reachable" in $$source)) {
            this["reachable"] = false;
        }
        if (!("sent" in $$source)) {
            this["sent"] = 0;
        }
        if (!("received" in $$source)) {
            this["received"] = 0;
        }
        if (!("lost" in $$source)) {
            this["lost"] = 0;
        }
        if (!("lossPercent" in $$source)) {
            this["lossPercent"] = 0;
        }
        if (!("avgLatencyMs" in $$source)) {
            this["avgLatencyMs"] = 0;
        }
        if (!("minLatencyMs" in $$source)) {
            this["minLatencyMs"] = 0;
        }
        if (!("maxLatencyMs" in $$source)) {
            this["maxLatencyMs"] = 0;
        }
        if (!("rawOutput" in $$source)) {
            this["rawOutput"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PingResult instance from a string or object.
     */
    static createFrom($$source: any = {}): PingResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PingResult($$parsedSource as Partial<PingResult>);
    }
}

export class Pod {
    "name": string;
    "namespace": string;
    "ready": string;
    "status": string;
    "restarts": number;
    "age": string;
    "node": string;

    /** Creates a new Pod instance. */
    constructor($$source: Partial<Pod> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("namespace" in $$source)) {
            this["namespace"] = "";
        }
        if (!("ready" in $$source)) {
            this["ready"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("restarts" in $$source)) {
            this["restarts"] = 0;
        }
        if (!("age" in $$source)) {
            this["age"] = "";
        }
        if (!("node" in $$source)) {
            this["node"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Pod instance from a string or object.
     */
    static createFrom($$source: any = {}): Pod {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Pod($$parsedSource as Partial<Pod>);
    }
}

export class PortScanResult {
    "target": string;
    "results": PortStatus[];

    /** Creates a new PortScanResult instance. */
    constructor($$source: Partial<PortScanResult> = {}) {
        if (!("target" in $$source)) {
            this["target"] = "";
        }
        if (!("results" in $$source)) {
            this["results"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PortScanResult instance from a string or object.
     */
    static createFrom($$source: any = {}): PortScanResult {
        const $$createField1_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("results" in $$parsedSource) {
            $$parsedSource["results"] = $$createField1_0($$parsedSource["results"]);
        }
        return new PortScanResult($$parsedSource as Partial<PortScanResult>);
    }
}

export class PortStatus {
    "port": number;
    "open": boolean;
    "latencyMs": number;
    "banner"?: string;

    /** Creates a new PortStatus instance. */
    constructor($$source: Partial<PortStatus> = {}) {
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("open" in $$source)) {
            this["open"] = false;
        }
        if (!("latencyMs" in $$source)) {
            this["latencyMs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PortStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): PortStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PortStatus($$parsedSource as Partial<PortStatus>);
    }
}

/**
 * ProcessInfo is a single row of the remote process table. We use the same
 * shape for all platforms even though we currently only parse Linux ps output;
 * adding macOS/BSD parsing later just fills these same fields.
 */
export class ProcessInfo {
    "pid": number;
    "ppid": number;
    "user": string;
    "cpuPct": number;
    "memPct": number;
    "rssKB": number;
    "state": string;
    "startTime": string;
    "command": string;

    /** Creates a new ProcessInfo instance. */
    constructor($$source: Partial<ProcessInfo> = {}) {
        if (!("pid" in $$source)) {
            this["pid"] = 0;
        }
        if (!("ppid" in $$source)) {
            this["ppid"] = 0;
        }
        if (!("user" in $$source)) {
            this["user"] = "";
        }
        if (!("cpuPct" in $$source)) {
            this["cpuPct"] = 0;
        }
        if (!("memPct" in $$source)) {
            this["memPct"] = 0;
        }
        if (!("rssKB" in $$source)) {
            this["rssKB"] = 0;
        }
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("startTime" in $$source)) {
            this["startTime"] = "";
        }
        if (!("command" in $$source)) {
            this["command"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProcessInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ProcessInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProcessInfo($$parsedSource as Partial<ProcessInfo>);
    }
}

/**
 * PublicKeyView is the safe shape returned to the frontend — never the
 * private material.
 */
export class PublicKeyView {
    "id": string;
    "name": string;
    "keyType": string;
    "publicKey": string;
    "fingerprint": string;
    "createdAt": number;

    /** Creates a new PublicKeyView instance. */
    constructor($$source: Partial<PublicKeyView> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("keyType" in $$source)) {
            this["keyType"] = "";
        }
        if (!("publicKey" in $$source)) {
            this["publicKey"] = "";
        }
        if (!("fingerprint" in $$source)) {
            this["fingerprint"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PublicKeyView instance from a string or object.
     */
    static createFrom($$source: any = {}): PublicKeyView {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PublicKeyView($$parsedSource as Partial<PublicKeyView>);
    }
}

export class QueryColumn {
    "name": string;
    "type": string;

    /** Creates a new QueryColumn instance. */
    constructor($$source: Partial<QueryColumn> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QueryColumn instance from a string or object.
     */
    static createFrom($$source: any = {}): QueryColumn {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new QueryColumn($$parsedSource as Partial<QueryColumn>);
    }
}

export class QueryResult {
    "columns": QueryColumn[];
    "rows": string[][];
    "rowCount": number;
    "truncated": boolean;
    "durationMs": number;
    "commandTag": string;

    /** Creates a new QueryResult instance. */
    constructor($$source: Partial<QueryResult> = {}) {
        if (!("columns" in $$source)) {
            this["columns"] = [];
        }
        if (!("rows" in $$source)) {
            this["rows"] = [];
        }
        if (!("rowCount" in $$source)) {
            this["rowCount"] = 0;
        }
        if (!("truncated" in $$source)) {
            this["truncated"] = false;
        }
        if (!("durationMs" in $$source)) {
            this["durationMs"] = 0;
        }
        if (!("commandTag" in $$source)) {
            this["commandTag"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QueryResult instance from a string or object.
     */
    static createFrom($$source: any = {}): QueryResult {
        const $$createField0_0 = $$createType10;
        const $$createField1_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField0_0($$parsedSource["columns"]);
        }
        if ("rows" in $$parsedSource) {
            $$parsedSource["rows"] = $$createField1_0($$parsedSource["rows"]);
        }
        return new QueryResult($$parsedSource as Partial<QueryResult>);
    }
}

export class RecordingDetail {
    "id": string;
    "title": string;
    "hostID"?: string;
    "hostName"?: string;
    "isLocal": boolean;
    "path": string;
    "startedAt": number;
    "endedAt": number;
    "durationSeconds": number;
    "sizeBytes": number;
    "width": number;
    "height": number;
    "events": CastEvent[];

    /** Creates a new RecordingDetail instance. */
    constructor($$source: Partial<RecordingDetail> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("isLocal" in $$source)) {
            this["isLocal"] = false;
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("startedAt" in $$source)) {
            this["startedAt"] = 0;
        }
        if (!("endedAt" in $$source)) {
            this["endedAt"] = 0;
        }
        if (!("durationSeconds" in $$source)) {
            this["durationSeconds"] = 0;
        }
        if (!("sizeBytes" in $$source)) {
            this["sizeBytes"] = 0;
        }
        if (!("width" in $$source)) {
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            this["height"] = 0;
        }
        if (!("events" in $$source)) {
            this["events"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RecordingDetail instance from a string or object.
     */
    static createFrom($$source: any = {}): RecordingDetail {
        const $$createField12_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("events" in $$parsedSource) {
            $$parsedSource["events"] = $$createField12_0($$parsedSource["events"]);
        }
        return new RecordingDetail($$parsedSource as Partial<RecordingDetail>);
    }
}

export class SFTPEntry {
    "name": string;
    "isDir": boolean;
    "size": number;
    "mode": string;
    "modTime": number;

    /** Creates a new SFTPEntry instance. */
    constructor($$source: Partial<SFTPEntry> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("isDir" in $$source)) {
            this["isDir"] = false;
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("modTime" in $$source)) {
            this["modTime"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SFTPEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): SFTPEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SFTPEntry($$parsedSource as Partial<SFTPEntry>);
    }
}

/**
 * SSHConfigCandidate is one Host block from the user's ~/.ssh/config that
 * could be imported as a saved host. Identity file is reported for context
 * — we don't auto-import key material (that's a separate vault flow).
 */
export class SSHConfigCandidate {
    "alias": string;
    "hostname": string;
    "user": string;
    "port": number;
    "identityFile": string;
    "proxyJump": string;

    /** Creates a new SSHConfigCandidate instance. */
    constructor($$source: Partial<SSHConfigCandidate> = {}) {
        if (!("alias" in $$source)) {
            this["alias"] = "";
        }
        if (!("hostname" in $$source)) {
            this["hostname"] = "";
        }
        if (!("user" in $$source)) {
            this["user"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("identityFile" in $$source)) {
            this["identityFile"] = "";
        }
        if (!("proxyJump" in $$source)) {
            this["proxyJump"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SSHConfigCandidate instance from a string or object.
     */
    static createFrom($$source: any = {}): SSHConfigCandidate {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SSHConfigCandidate($$parsedSource as Partial<SSHConfigCandidate>);
    }
}

/**
 * SSHConnectOptions is the ad-hoc connect payload — used when the user types
 * host/user/password directly in the terminal toolbar instead of picking from
 * the saved-host list.
 */
export class SSHConnectOptions {
    "Host": string;
    "Port": number;
    "User": string;

    /**
     * "password" | "key" | "agent"
     */
    "AuthMethod": string;
    "Password": string;
    "KeyID": string;
    "Cols": number;
    "Rows": number;

    /** Creates a new SSHConnectOptions instance. */
    constructor($$source: Partial<SSHConnectOptions> = {}) {
        if (!("Host" in $$source)) {
            this["Host"] = "";
        }
        if (!("Port" in $$source)) {
            this["Port"] = 0;
        }
        if (!("User" in $$source)) {
            this["User"] = "";
        }
        if (!("AuthMethod" in $$source)) {
            this["AuthMethod"] = "";
        }
        if (!("Password" in $$source)) {
            this["Password"] = "";
        }
        if (!("KeyID" in $$source)) {
            this["KeyID"] = "";
        }
        if (!("Cols" in $$source)) {
            this["Cols"] = 0;
        }
        if (!("Rows" in $$source)) {
            this["Rows"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SSHConnectOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): SSHConnectOptions {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SSHConnectOptions($$parsedSource as Partial<SSHConnectOptions>);
    }
}

export class SSLResult {
    "target": string;
    "handshakeOK": boolean;
    "tlsVersion": string;
    "cipherSuite": string;
    "cert": CertInfo;
    "error"?: string;

    /** Creates a new SSLResult instance. */
    constructor($$source: Partial<SSLResult> = {}) {
        if (!("target" in $$source)) {
            this["target"] = "";
        }
        if (!("handshakeOK" in $$source)) {
            this["handshakeOK"] = false;
        }
        if (!("tlsVersion" in $$source)) {
            this["tlsVersion"] = "";
        }
        if (!("cipherSuite" in $$source)) {
            this["cipherSuite"] = "";
        }
        if (!("cert" in $$source)) {
            this["cert"] = (new CertInfo());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SSLResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SSLResult {
        const $$createField4_0 = $$createType14;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("cert" in $$parsedSource) {
            $$parsedSource["cert"] = $$createField4_0($$parsedSource["cert"]);
        }
        return new SSLResult($$parsedSource as Partial<SSLResult>);
    }
}

/**
 * SavedConnection is the wire-safe view of a stored connection record.
 */
export class SavedConnection {
    "id": string;
    "name": string;
    "kind": string;
    "hostID": string;
    "hostName": string;
    "createdAt": number;

    /** Creates a new SavedConnection instance. */
    constructor($$source: Partial<SavedConnection> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("hostID" in $$source)) {
            this["hostID"] = "";
        }
        if (!("hostName" in $$source)) {
            this["hostName"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SavedConnection instance from a string or object.
     */
    static createFrom($$source: any = {}): SavedConnection {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SavedConnection($$parsedSource as Partial<SavedConnection>);
    }
}

/**
 * SearchHit ties a recording to one or more matched lines for the search UI.
 */
export class SearchHit {
    "recording": store$0.Recording;
    "matches": recorder$0.Match[];

    /** Creates a new SearchHit instance. */
    constructor($$source: Partial<SearchHit> = {}) {
        if (!("recording" in $$source)) {
            this["recording"] = (new store$0.Recording());
        }
        if (!("matches" in $$source)) {
            this["matches"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchHit instance from a string or object.
     */
    static createFrom($$source: any = {}): SearchHit {
        const $$createField0_0 = $$createType15;
        const $$createField1_0 = $$createType17;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("recording" in $$parsedSource) {
            $$parsedSource["recording"] = $$createField0_0($$parsedSource["recording"]);
        }
        if ("matches" in $$parsedSource) {
            $$parsedSource["matches"] = $$createField1_0($$parsedSource["matches"]);
        }
        return new SearchHit($$parsedSource as Partial<SearchHit>);
    }
}

/**
 * Validate is a small helper the UI can call before saving — surfaces
 * undefined-default warnings, which a future rev could escalate to errors.
 */
export class SnippetValidation {
    "variables": SnippetVariable[];
    "warnings": string[];

    /** Creates a new SnippetValidation instance. */
    constructor($$source: Partial<SnippetValidation> = {}) {
        if (!("variables" in $$source)) {
            this["variables"] = [];
        }
        if (!("warnings" in $$source)) {
            this["warnings"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SnippetValidation instance from a string or object.
     */
    static createFrom($$source: any = {}): SnippetValidation {
        const $$createField0_0 = $$createType19;
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("variables" in $$parsedSource) {
            $$parsedSource["variables"] = $$createField0_0($$parsedSource["variables"]);
        }
        if ("warnings" in $$parsedSource) {
            $$parsedSource["warnings"] = $$createField1_0($$parsedSource["warnings"]);
        }
        return new SnippetValidation($$parsedSource as Partial<SnippetValidation>);
    }
}

/**
 * SnippetVariable describes one {{var}} or {{var|default}} placeholder found
 * in a snippet body, deduplicated, in first-occurrence order.
 */
export class SnippetVariable {
    "name": string;
    "default": string;

    /** Creates a new SnippetVariable instance. */
    constructor($$source: Partial<SnippetVariable> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("default" in $$source)) {
            this["default"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SnippetVariable instance from a string or object.
     */
    static createFrom($$source: any = {}): SnippetVariable {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SnippetVariable($$parsedSource as Partial<SnippetVariable>);
    }
}

/**
 * SyncSettings is the persisted config (endpoint URL, bearer token). The
 * token is stored under the existing settings KV store; we reuse the
 * vault for encryption-at-rest.
 */
export class SyncSettings {
    "endpoint": string;
    "token": string;

    /** Creates a new SyncSettings instance. */
    constructor($$source: Partial<SyncSettings> = {}) {
        if (!("endpoint" in $$source)) {
            this["endpoint"] = "";
        }
        if (!("token" in $$source)) {
            this["token"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SyncSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): SyncSettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SyncSettings($$parsedSource as Partial<SyncSettings>);
    }
}

/**
 * SyncStatus is what the UI renders.
 */
export class SyncStatus {
    "configured": boolean;
    "endpoint": string;
    "lastPushAt": number;
    "lastPullAt": number;
    "lastError"?: string;

    /** Creates a new SyncStatus instance. */
    constructor($$source: Partial<SyncStatus> = {}) {
        if (!("configured" in $$source)) {
            this["configured"] = false;
        }
        if (!("endpoint" in $$source)) {
            this["endpoint"] = "";
        }
        if (!("lastPushAt" in $$source)) {
            this["lastPushAt"] = 0;
        }
        if (!("lastPullAt" in $$source)) {
            this["lastPullAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SyncStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): SyncStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SyncStatus($$parsedSource as Partial<SyncStatus>);
    }
}

/**
 * SystemdUnit is a single systemctl-listed service. ActiveState is what most
 * people mean by "is it running": active / inactive / failed.
 */
export class SystemdUnit {
    "name": string;
    "loadState": string;
    "activeState": string;
    "subState": string;
    "description": string;

    /** Creates a new SystemdUnit instance. */
    constructor($$source: Partial<SystemdUnit> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("loadState" in $$source)) {
            this["loadState"] = "";
        }
        if (!("activeState" in $$source)) {
            this["activeState"] = "";
        }
        if (!("subState" in $$source)) {
            this["subState"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SystemdUnit instance from a string or object.
     */
    static createFrom($$source: any = {}): SystemdUnit {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SystemdUnit($$parsedSource as Partial<SystemdUnit>);
    }
}

export class TerminalData {
    "sessionID": string;
    "data": string;

    /** Creates a new TerminalData instance. */
    constructor($$source: Partial<TerminalData> = {}) {
        if (!("sessionID" in $$source)) {
            this["sessionID"] = "";
        }
        if (!("data" in $$source)) {
            this["data"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TerminalData instance from a string or object.
     */
    static createFrom($$source: any = {}): TerminalData {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TerminalData($$parsedSource as Partial<TerminalData>);
    }
}

export class TerminalExit {
    "sessionID": string;
    "reason": string;

    /** Creates a new TerminalExit instance. */
    constructor($$source: Partial<TerminalExit> = {}) {
        if (!("sessionID" in $$source)) {
            this["sessionID"] = "";
        }
        if (!("reason" in $$source)) {
            this["reason"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TerminalExit instance from a string or object.
     */
    static createFrom($$source: any = {}): TerminalExit {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TerminalExit($$parsedSource as Partial<TerminalExit>);
    }
}

/**
 * UpdateInfo is the wire shape returned to the frontend. Empty `Latest`
 * + non-empty `Error` indicates the probe failed — the UI should surface
 * that state rather than silently treating it as "you're up to date".
 */
export class UpdateInfo {
    "current": string;
    "latest": string;
    "updateAvailable": boolean;
    "releaseUrl": string;
    "notes"?: string;
    "publishedAt"?: string;
    "error"?: string;

    /** Creates a new UpdateInfo instance. */
    constructor($$source: Partial<UpdateInfo> = {}) {
        if (!("current" in $$source)) {
            this["current"] = "";
        }
        if (!("latest" in $$source)) {
            this["latest"] = "";
        }
        if (!("updateAvailable" in $$source)) {
            this["updateAvailable"] = false;
        }
        if (!("releaseUrl" in $$source)) {
            this["releaseUrl"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateInfo($$parsedSource as Partial<UpdateInfo>);
    }
}

/**
 * VaultLockEvent is emitted when the vault auto-locks so the UI can navigate
 * back to the unlock screen even if no one was watching.
 */
export class VaultLockEvent {
    "reason": string;

    /** Creates a new VaultLockEvent instance. */
    constructor($$source: Partial<VaultLockEvent> = {}) {
        if (!("reason" in $$source)) {
            this["reason"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VaultLockEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): VaultLockEvent {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VaultLockEvent($$parsedSource as Partial<VaultLockEvent>);
    }
}

export class VaultStatus {
    "initialized": boolean;
    "unlocked": boolean;

    /** Creates a new VaultStatus instance. */
    constructor($$source: Partial<VaultStatus> = {}) {
        if (!("initialized" in $$source)) {
            this["initialized"] = false;
        }
        if (!("unlocked" in $$source)) {
            this["unlocked"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VaultStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): VaultStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VaultStatus($$parsedSource as Partial<VaultStatus>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = DNSAnswer.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = ExecResult.createFrom;
const $$createType4 = $Create.Map($Create.Any, $Create.Any);
const $$createType5 = HTTPHeader.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = PortStatus.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = QueryColumn.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = $Create.Array($$createType0);
const $$createType12 = CastEvent.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = CertInfo.createFrom;
const $$createType15 = store$0.Recording.createFrom;
const $$createType16 = recorder$0.Match.createFrom;
const $$createType17 = $Create.Array($$createType16);
const $$createType18 = SnippetVariable.createFrom;
const $$createType19 = $Create.Array($$createType18);
