// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AIChunk is the streaming payload — the frontend appends `delta` text to the
 * currently-rendering message and uses `done` to know when to stop.
 */
export class AIChunk {
    /**
     * Creates a new AIChunk instance.
     * @param {Partial<AIChunk>} [$$source = {}] - The source object to create the AIChunk.
     */
    constructor($$source = {}) {
        if (!("streamID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["streamID"] = "";
        }
        if (!("delta" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["delta"] = "";
        }
        if (!("done" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["done"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIChunk instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AIChunk}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AIChunk(/** @type {Partial<AIChunk>} */($$parsedSource));
    }
}

/**
 * AppSettings is the safe shape returned to the frontend — never includes
 * raw secrets, just whether each one is set.
 */
export class AppSettings {
    /**
     * Creates a new AppSettings instance.
     * @param {Partial<AppSettings>} [$$source = {}] - The source object to create the AppSettings.
     */
    constructor($$source = {}) {
        if (!("theme" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["theme"] = "";
        }
        if (!("autoLockMinutes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["autoLockMinutes"] = 0;
        }
        if (!("defaultShellPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["defaultShellPath"] = "";
        }
        if (!("metricsIntervalSeconds" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["metricsIntervalSeconds"] = 0;
        }
        if (!("hasAnthropicKey" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hasAnthropicKey"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppSettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AppSettings}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppSettings(/** @type {Partial<AppSettings>} */($$parsedSource));
    }
}

export class ExecProgress {
    /**
     * Creates a new ExecProgress instance.
     * @param {Partial<ExecProgress>} [$$source = {}] - The source object to create the ExecProgress.
     */
    constructor($$source = {}) {
        if (!("runID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["runID"] = "";
        }
        if (!("result" in $$source)) {
            /**
             * @member
             * @type {ExecResult}
             */
            this["result"] = (new ExecResult());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExecProgress instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ExecProgress}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("result" in $$parsedSource) {
            $$parsedSource["result"] = $$createField1_0($$parsedSource["result"]);
        }
        return new ExecProgress(/** @type {Partial<ExecProgress>} */($$parsedSource));
    }
}

/**
 * ExecResult is the per-host outcome of a multi-host run.
 */
export class ExecResult {
    /**
     * Creates a new ExecResult instance.
     * @param {Partial<ExecResult>} [$$source = {}] - The source object to create the ExecResult.
     */
    constructor($$source = {}) {
        if (!("hostID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hostID"] = "";
        }
        if (!("hostName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hostName"] = "";
        }
        if (!("stdout" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["stdout"] = "";
        }
        if (!("stderr" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["stderr"] = "";
        }
        if (!("exitCode" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["exitCode"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (!("attempts" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["attempts"] = 0;
        }
        if (!("durationMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["durationMs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExecResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ExecResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ExecResult(/** @type {Partial<ExecResult>} */($$parsedSource));
    }
}

export class HostMetrics {
    /**
     * Creates a new HostMetrics instance.
     * @param {Partial<HostMetrics>} [$$source = {}] - The source object to create the HostMetrics.
     */
    constructor($$source = {}) {
        if (!("hostID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hostID"] = "";
        }
        if (!("hostName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hostName"] = "";
        }
        if (!("online" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["online"] = false;
        }
        if (!("cpuPercent" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["cpuPercent"] = 0;
        }
        if (!("memPercent" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["memPercent"] = 0;
        }
        if (!("diskPercent" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["diskPercent"] = 0;
        }
        if (!("loadAvg1" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["loadAvg1"] = 0;
        }
        if (!("timestamp" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["timestamp"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HostMetrics instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HostMetrics}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HostMetrics(/** @type {Partial<HostMetrics>} */($$parsedSource));
    }
}

/**
 * LogLine is the per-line payload streamed to the frontend during a log run.
 * Lines from multiple hosts share a single streamID so the UI can colocate
 * them in one view, and each line carries its hostName so the UI can colour /
 * label without a second lookup.
 */
export class LogLine {
    /**
     * Creates a new LogLine instance.
     * @param {Partial<LogLine>} [$$source = {}] - The source object to create the LogLine.
     */
    constructor($$source = {}) {
        if (!("streamID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["streamID"] = "";
        }
        if (!("hostID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hostID"] = "";
        }
        if (!("hostName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hostName"] = "";
        }
        if (!("line" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["line"] = "";
        }
        if (!("isStderr" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isStderr"] = false;
        }
        if (!("timestamp" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["timestamp"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogLine instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LogLine}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LogLine(/** @type {Partial<LogLine>} */($$parsedSource));
    }
}

/**
 * PublicKeyView is the safe shape returned to the frontend — never the
 * private material.
 */
export class PublicKeyView {
    /**
     * Creates a new PublicKeyView instance.
     * @param {Partial<PublicKeyView>} [$$source = {}] - The source object to create the PublicKeyView.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("keyType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["keyType"] = "";
        }
        if (!("publicKey" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["publicKey"] = "";
        }
        if (!("fingerprint" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fingerprint"] = "";
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["createdAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PublicKeyView instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PublicKeyView}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PublicKeyView(/** @type {Partial<PublicKeyView>} */($$parsedSource));
    }
}

export class SFTPEntry {
    /**
     * Creates a new SFTPEntry instance.
     * @param {Partial<SFTPEntry>} [$$source = {}] - The source object to create the SFTPEntry.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("isDir" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isDir"] = false;
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }
        if (!("mode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["mode"] = "";
        }
        if (!("modTime" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["modTime"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SFTPEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SFTPEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SFTPEntry(/** @type {Partial<SFTPEntry>} */($$parsedSource));
    }
}

/**
 * SSHConnectOptions is the ad-hoc connect payload — used when the user types
 * host/user/password directly in the terminal toolbar instead of picking from
 * the saved-host list.
 */
export class SSHConnectOptions {
    /**
     * Creates a new SSHConnectOptions instance.
     * @param {Partial<SSHConnectOptions>} [$$source = {}] - The source object to create the SSHConnectOptions.
     */
    constructor($$source = {}) {
        if (!("Host" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Host"] = "";
        }
        if (!("Port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Port"] = 0;
        }
        if (!("User" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["User"] = "";
        }
        if (!("AuthMethod" in $$source)) {
            /**
             * "password" | "key" | "agent"
             * @member
             * @type {string}
             */
            this["AuthMethod"] = "";
        }
        if (!("Password" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Password"] = "";
        }
        if (!("KeyID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["KeyID"] = "";
        }
        if (!("Cols" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Cols"] = 0;
        }
        if (!("Rows" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Rows"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SSHConnectOptions instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SSHConnectOptions}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SSHConnectOptions(/** @type {Partial<SSHConnectOptions>} */($$parsedSource));
    }
}

export class TerminalData {
    /**
     * Creates a new TerminalData instance.
     * @param {Partial<TerminalData>} [$$source = {}] - The source object to create the TerminalData.
     */
    constructor($$source = {}) {
        if (!("sessionID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sessionID"] = "";
        }
        if (!("data" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["data"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TerminalData instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TerminalData}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TerminalData(/** @type {Partial<TerminalData>} */($$parsedSource));
    }
}

export class TerminalExit {
    /**
     * Creates a new TerminalExit instance.
     * @param {Partial<TerminalExit>} [$$source = {}] - The source object to create the TerminalExit.
     */
    constructor($$source = {}) {
        if (!("sessionID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sessionID"] = "";
        }
        if (!("reason" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["reason"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TerminalExit instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TerminalExit}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TerminalExit(/** @type {Partial<TerminalExit>} */($$parsedSource));
    }
}

/**
 * VaultLockEvent is emitted when the vault auto-locks so the UI can navigate
 * back to the unlock screen even if no one was watching.
 */
export class VaultLockEvent {
    /**
     * Creates a new VaultLockEvent instance.
     * @param {Partial<VaultLockEvent>} [$$source = {}] - The source object to create the VaultLockEvent.
     */
    constructor($$source = {}) {
        if (!("reason" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["reason"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VaultLockEvent instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {VaultLockEvent}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VaultLockEvent(/** @type {Partial<VaultLockEvent>} */($$parsedSource));
    }
}

export class VaultStatus {
    /**
     * Creates a new VaultStatus instance.
     * @param {Partial<VaultStatus>} [$$source = {}] - The source object to create the VaultStatus.
     */
    constructor($$source = {}) {
        if (!("initialized" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["initialized"] = false;
        }
        if (!("unlocked" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["unlocked"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VaultStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {VaultStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VaultStatus(/** @type {Partial<VaultStatus>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = ExecResult.createFrom;
