// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as recorder$0 from "./internal/recorder/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "./internal/store/models.js";

/**
 * AIChunk is the streaming payload — the frontend appends `delta` text to the
 * currently-rendering message and uses `done` to know when to stop.
 */
export class AIChunk {
    /**
     * Creates a new AIChunk instance.
     * @param {Partial<AIChunk>} [$$source = {}] - The source object to create the AIChunk.
     */
    constructor($$source = {}) {
        if (!("streamID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["streamID"] = "";
        }
        if (!("delta" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["delta"] = "";
        }
        if (!("done" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["done"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIChunk instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AIChunk}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AIChunk(/** @type {Partial<AIChunk>} */($$parsedSource));
    }
}

/**
 * ActiveForward bundles a saved forward with its current runtime state.
 */
export class ActiveForward {
    /**
     * Creates a new ActiveForward instance.
     * @param {Partial<ActiveForward>} [$$source = {}] - The source object to create the ActiveForward.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("hostID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hostID"] = "";
        }
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {store$0.ForwardKind}
             */
            this["kind"] = store$0.ForwardKind.$zero;
        }
        if (!("localAddr" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["localAddr"] = "";
        }
        if (!("localPort" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["localPort"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["remoteAddr"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["remotePort"] = undefined;
        }
        if (!("autoStart" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["autoStart"] = false;
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["createdAt"] = 0;
        }
        if (!("active" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["active"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ActiveForward instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ActiveForward}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ActiveForward(/** @type {Partial<ActiveForward>} */($$parsedSource));
    }
}

/**
 * AppSettings is the safe shape returned to the frontend — never includes
 * raw secrets, just whether each one is set.
 */
export class AppSettings {
    /**
     * Creates a new AppSettings instance.
     * @param {Partial<AppSettings>} [$$source = {}] - The source object to create the AppSettings.
     */
    constructor($$source = {}) {
        if (!("theme" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["theme"] = "";
        }
        if (!("autoLockMinutes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["autoLockMinutes"] = 0;
        }
        if (!("defaultShellPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["defaultShellPath"] = "";
        }
        if (!("metricsIntervalSeconds" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["metricsIntervalSeconds"] = 0;
        }
        if (!("hasAnthropicKey" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hasAnthropicKey"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppSettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AppSettings}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppSettings(/** @type {Partial<AppSettings>} */($$parsedSource));
    }
}

/**
 * CastEvent is the over-the-wire shape of a single playback event. The cast
 * internal type uses a custom MarshalJSON for asciinema compatibility, which
 * the Wails binding generator can't introspect — this struct is the "wire"
 * view used when handing events to the frontend.
 */
export class CastEvent {
    /**
     * Creates a new CastEvent instance.
     * @param {Partial<CastEvent>} [$$source = {}] - The source object to create the CastEvent.
     */
    constructor($$source = {}) {
        if (!("offset" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["offset"] = 0;
        }
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (!("data" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["data"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CastEvent instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CastEvent}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CastEvent(/** @type {Partial<CastEvent>} */($$parsedSource));
    }
}

export class CertInfo {
    /**
     * Creates a new CertInfo instance.
     * @param {Partial<CertInfo>} [$$source = {}] - The source object to create the CertInfo.
     */
    constructor($$source = {}) {
        if (!("subject" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["subject"] = "";
        }
        if (!("issuer" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["issuer"] = "";
        }
        if (!("notBefore" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["notBefore"] = 0;
        }
        if (!("notAfter" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["notAfter"] = 0;
        }
        if (!("daysUntilExpiry" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["daysUntilExpiry"] = 0;
        }
        if (!("dnsNames" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["dnsNames"] = [];
        }
        if (!("fingerprint" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fingerprint"] = "";
        }
        if (!("serialNumber" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["serialNumber"] = "";
        }
        if (!("chain" in $$source)) {
            /**
             * each peer subject, leaf-first
             * @member
             * @type {string[]}
             */
            this["chain"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CertInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CertInfo}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType0;
        const $$createField8_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("dnsNames" in $$parsedSource) {
            $$parsedSource["dnsNames"] = $$createField5_0($$parsedSource["dnsNames"]);
        }
        if ("chain" in $$parsedSource) {
            $$parsedSource["chain"] = $$createField8_0($$parsedSource["chain"]);
        }
        return new CertInfo(/** @type {Partial<CertInfo>} */($$parsedSource));
    }
}

/**
 * Container is the wire shape returned to the frontend. We deliberately keep
 * this language-agnostic — Docker, Podman, and Kubernetes pods all map onto it.
 */
export class Container {
    /**
     * Creates a new Container instance.
     * @param {Partial<Container>} [$$source = {}] - The source object to create the Container.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("image" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["image"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("state" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["state"] = "";
        }
        if (!("ports" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ports"] = "";
        }
        if (!("created" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["created"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Container instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Container}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Container(/** @type {Partial<Container>} */($$parsedSource));
    }
}

/**
 * DBColumn describes one column for the schema browser's column drawer.
 */
export class DBColumn {
    /**
     * Creates a new DBColumn instance.
     * @param {Partial<DBColumn>} [$$source = {}] - The source object to create the DBColumn.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("dataType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["dataType"] = "";
        }
        if (!("nullable" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["nullable"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["default"] = undefined;
        }
        if (!("isPrimary" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isPrimary"] = false;
        }
        if (!("ordinalPos" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ordinalPos"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DBColumn instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DBColumn}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DBColumn(/** @type {Partial<DBColumn>} */($$parsedSource));
    }
}

/**
 * DBConnectionInfo is the safe view of an open connection — enough to render
 * "you're connected to X as Y" without surfacing the password back to the UI.
 */
export class DBConnectionInfo {
    /**
     * Creates a new DBConnectionInfo instance.
     * @param {Partial<DBConnectionInfo>} [$$source = {}] - The source object to create the DBConnectionInfo.
     */
    constructor($$source = {}) {
        if (!("connID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["connID"] = "";
        }
        if (!("kind" in $$source)) {
            /**
             * "postgres" | "mysql"
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (!("hostID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hostID"] = "";
        }
        if (!("hostName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hostName"] = "";
        }
        if (!("database" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["database"] = "";
        }
        if (!("user" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["user"] = "";
        }
        if (!("server" in $$source)) {
            /**
             * host:port from the DSN
             * @member
             * @type {string}
             */
            this["server"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DBConnectionInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DBConnectionInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DBConnectionInfo(/** @type {Partial<DBConnectionInfo>} */($$parsedSource));
    }
}

/**
 * DBTable is one entry in the schema browser. RowEstimate is best-effort —
 * information_schema gives an estimate on Postgres (pg_class.reltuples) and
 * the storage engine's running estimate on MySQL (TABLE_ROWS), neither of
 * which is exact for active tables.
 */
export class DBTable {
    /**
     * Creates a new DBTable instance.
     * @param {Partial<DBTable>} [$$source = {}] - The source object to create the DBTable.
     */
    constructor($$source = {}) {
        if (!("schema" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["schema"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("kind" in $$source)) {
            /**
             * "table" | "view"
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (!("rowEstimate" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["rowEstimate"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DBTable instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DBTable}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DBTable(/** @type {Partial<DBTable>} */($$parsedSource));
    }
}

export class DNSAnswer {
    /**
     * Creates a new DNSAnswer instance.
     * @param {Partial<DNSAnswer>} [$$source = {}] - The source object to create the DNSAnswer.
     */
    constructor($$source = {}) {
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("value" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["value"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DNSAnswer instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DNSAnswer}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DNSAnswer(/** @type {Partial<DNSAnswer>} */($$parsedSource));
    }
}

export class DNSResult {
    /**
     * Creates a new DNSResult instance.
     * @param {Partial<DNSResult>} [$$source = {}] - The source object to create the DNSResult.
     */
    constructor($$source = {}) {
        if (!("target" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["target"] = "";
        }
        if (!("answers" in $$source)) {
            /**
             * @member
             * @type {DNSAnswer[]}
             */
            this["answers"] = [];
        }
        if (!("rawOutput" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["rawOutput"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DNSResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DNSResult}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("answers" in $$parsedSource) {
            $$parsedSource["answers"] = $$createField1_0($$parsedSource["answers"]);
        }
        return new DNSResult(/** @type {Partial<DNSResult>} */($$parsedSource));
    }
}

export class ExecProgress {
    /**
     * Creates a new ExecProgress instance.
     * @param {Partial<ExecProgress>} [$$source = {}] - The source object to create the ExecProgress.
     */
    constructor($$source = {}) {
        if (!("runID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["runID"] = "";
        }
        if (!("result" in $$source)) {
            /**
             * @member
             * @type {ExecResult}
             */
            this["result"] = (new ExecResult());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExecProgress instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ExecProgress}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("result" in $$parsedSource) {
            $$parsedSource["result"] = $$createField1_0($$parsedSource["result"]);
        }
        return new ExecProgress(/** @type {Partial<ExecProgress>} */($$parsedSource));
    }
}

/**
 * ExecResult is the per-host outcome of a multi-host run.
 */
export class ExecResult {
    /**
     * Creates a new ExecResult instance.
     * @param {Partial<ExecResult>} [$$source = {}] - The source object to create the ExecResult.
     */
    constructor($$source = {}) {
        if (!("hostID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hostID"] = "";
        }
        if (!("hostName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hostName"] = "";
        }
        if (!("stdout" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["stdout"] = "";
        }
        if (!("stderr" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["stderr"] = "";
        }
        if (!("exitCode" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["exitCode"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (!("attempts" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["attempts"] = 0;
        }
        if (!("durationMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["durationMs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExecResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ExecResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ExecResult(/** @type {Partial<ExecResult>} */($$parsedSource));
    }
}

/**
 * HTTPHeader is one response header. Flat (name, value) pairs preserve the
 * order the server sent (map iteration would lose it).
 */
export class HTTPHeader {
    /**
     * Creates a new HTTPHeader instance.
     * @param {Partial<HTTPHeader>} [$$source = {}] - The source object to create the HTTPHeader.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("value" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["value"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HTTPHeader instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HTTPHeader}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HTTPHeader(/** @type {Partial<HTTPHeader>} */($$parsedSource));
    }
}

/**
 * HTTPRequestOptions is the wire shape from the frontend. We accept headers
 * as a flat map of single values (the multi-value rare-case is rejected on
 * the way out — most ops debugging fits this shape and the UI is simpler).
 */
export class HTTPRequestOptions {
    /**
     * Creates a new HTTPRequestOptions instance.
     * @param {Partial<HTTPRequestOptions>} [$$source = {}] - The source object to create the HTTPRequestOptions.
     */
    constructor($$source = {}) {
        if (!("method" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["method"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("headers" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: string }}
             */
            this["headers"] = {};
        }
        if (!("body" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["body"] = "";
        }
        if (!("insecureSkipVerify" in $$source)) {
            /**
             * Skip TLS verification for the request. The SSL cert inspector and the
             * browser do this too — this is a debug tool, not a security boundary.
             * @member
             * @type {boolean}
             */
            this["insecureSkipVerify"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HTTPRequestOptions instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HTTPRequestOptions}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("headers" in $$parsedSource) {
            $$parsedSource["headers"] = $$createField2_0($$parsedSource["headers"]);
        }
        return new HTTPRequestOptions(/** @type {Partial<HTTPRequestOptions>} */($$parsedSource));
    }
}

export class HTTPResponse {
    /**
     * Creates a new HTTPResponse instance.
     * @param {Partial<HTTPResponse>} [$$source = {}] - The source object to create the HTTPResponse.
     */
    constructor($$source = {}) {
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["status"] = 0;
        }
        if (!("statusText" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["statusText"] = "";
        }
        if (!("proto" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["proto"] = "";
        }
        if (!("headers" in $$source)) {
            /**
             * @member
             * @type {HTTPHeader[]}
             */
            this["headers"] = [];
        }
        if (!("body" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["body"] = "";
        }
        if (!("bodyBase64" in $$source)) {
            /**
             * true if Body is base64 (binary response)
             * @member
             * @type {boolean}
             */
            this["bodyBase64"] = false;
        }
        if (!("sizeBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sizeBytes"] = 0;
        }
        if (!("truncated" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["truncated"] = false;
        }
        if (!("durationMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["durationMs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HTTPResponse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HTTPResponse}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("headers" in $$parsedSource) {
            $$parsedSource["headers"] = $$createField3_0($$parsedSource["headers"]);
        }
        return new HTTPResponse(/** @type {Partial<HTTPResponse>} */($$parsedSource));
    }
}

export class HostMetrics {
    /**
     * Creates a new HostMetrics instance.
     * @param {Partial<HostMetrics>} [$$source = {}] - The source object to create the HostMetrics.
     */
    constructor($$source = {}) {
        if (!("hostID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hostID"] = "";
        }
        if (!("hostName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hostName"] = "";
        }
        if (!("online" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["online"] = false;
        }
        if (!("cpuPercent" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["cpuPercent"] = 0;
        }
        if (!("memPercent" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["memPercent"] = 0;
        }
        if (!("diskPercent" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["diskPercent"] = 0;
        }
        if (!("loadAvg1" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["loadAvg1"] = 0;
        }
        if (!("rxBytesPerSec" in $$source)) {
            /**
             * Network throughput averaged over the interval since the previous tick.
             * Aggregated across all non-loopback interfaces. First sample after Start
             * has rates of zero (no prior to compare against).
             * @member
             * @type {number}
             */
            this["rxBytesPerSec"] = 0;
        }
        if (!("txBytesPerSec" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["txBytesPerSec"] = 0;
        }
        if (!("rxBytesTotal" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["rxBytesTotal"] = 0;
        }
        if (!("txBytesTotal" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["txBytesTotal"] = 0;
        }
        if (!("timestamp" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["timestamp"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HostMetrics instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HostMetrics}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HostMetrics(/** @type {Partial<HostMetrics>} */($$parsedSource));
    }
}

/**
 * LogLine is the per-line payload streamed to the frontend during a log run.
 * Lines from multiple hosts share a single streamID so the UI can colocate
 * them in one view, and each line carries its hostName so the UI can colour /
 * label without a second lookup.
 */
export class LogLine {
    /**
     * Creates a new LogLine instance.
     * @param {Partial<LogLine>} [$$source = {}] - The source object to create the LogLine.
     */
    constructor($$source = {}) {
        if (!("streamID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["streamID"] = "";
        }
        if (!("hostID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hostID"] = "";
        }
        if (!("hostName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hostName"] = "";
        }
        if (!("line" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["line"] = "";
        }
        if (!("isStderr" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isStderr"] = false;
        }
        if (!("timestamp" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["timestamp"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogLine instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LogLine}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LogLine(/** @type {Partial<LogLine>} */($$parsedSource));
    }
}

/**
 * Notification is the wire shape: matches what the in-app toast renders and
 * what the webhook receives.
 */
export class Notification {
    /**
     * Creates a new Notification instance.
     * @param {Partial<Notification>} [$$source = {}] - The source object to create the Notification.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {NotifyKind}
             */
            this["kind"] = NotifyKind.$zero;
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("body" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["body"] = "";
        }
        if (!("source" in $$source)) {
            /**
             * "exec" | "metrics" | "test" | etc.
             * @member
             * @type {string}
             */
            this["source"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["hostName"] = undefined;
        }
        if (!("timestamp" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["timestamp"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Notification instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Notification}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Notification(/** @type {Partial<Notification>} */($$parsedSource));
    }
}

/**
 * NotifyConfig is what we expose to the frontend Settings panel.
 */
export class NotifyConfig {
    /**
     * Creates a new NotifyConfig instance.
     * @param {Partial<NotifyConfig>} [$$source = {}] - The source object to create the NotifyConfig.
     */
    constructor($$source = {}) {
        if (!("desktopEnabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["desktopEnabled"] = false;
        }
        if (!("webhookURL" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["webhookURL"] = "";
        }
        if (!("longExecSeconds" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["longExecSeconds"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NotifyConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {NotifyConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NotifyConfig(/** @type {Partial<NotifyConfig>} */($$parsedSource));
    }
}

/**
 * NotifyKind classifies the notification so the UI can pick an icon/colour.
 * @readonly
 * @enum {string}
 */
export const NotifyKind = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    NotifyInfo: "info",
    NotifyOK: "ok",
    NotifyWarn: "warn",
    NotifyError: "error",
};

export class PingResult {
    /**
     * Creates a new PingResult instance.
     * @param {Partial<PingResult>} [$$source = {}] - The source object to create the PingResult.
     */
    constructor($$source = {}) {
        if (!("target" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["target"] = "";
        }
        if (!("reachable" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["reachable"] = false;
        }
        if (!("sent" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sent"] = 0;
        }
        if (!("received" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["received"] = 0;
        }
        if (!("lost" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["lost"] = 0;
        }
        if (!("lossPercent" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["lossPercent"] = 0;
        }
        if (!("avgLatencyMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["avgLatencyMs"] = 0;
        }
        if (!("minLatencyMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["minLatencyMs"] = 0;
        }
        if (!("maxLatencyMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["maxLatencyMs"] = 0;
        }
        if (!("rawOutput" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["rawOutput"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PingResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PingResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PingResult(/** @type {Partial<PingResult>} */($$parsedSource));
    }
}

export class Pod {
    /**
     * Creates a new Pod instance.
     * @param {Partial<Pod>} [$$source = {}] - The source object to create the Pod.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("namespace" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["namespace"] = "";
        }
        if (!("ready" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ready"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("restarts" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["restarts"] = 0;
        }
        if (!("age" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["age"] = "";
        }
        if (!("node" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["node"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Pod instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Pod}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Pod(/** @type {Partial<Pod>} */($$parsedSource));
    }
}

export class PortScanResult {
    /**
     * Creates a new PortScanResult instance.
     * @param {Partial<PortScanResult>} [$$source = {}] - The source object to create the PortScanResult.
     */
    constructor($$source = {}) {
        if (!("target" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["target"] = "";
        }
        if (!("results" in $$source)) {
            /**
             * @member
             * @type {PortStatus[]}
             */
            this["results"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PortScanResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PortScanResult}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("results" in $$parsedSource) {
            $$parsedSource["results"] = $$createField1_0($$parsedSource["results"]);
        }
        return new PortScanResult(/** @type {Partial<PortScanResult>} */($$parsedSource));
    }
}

export class PortStatus {
    /**
     * Creates a new PortStatus instance.
     * @param {Partial<PortStatus>} [$$source = {}] - The source object to create the PortStatus.
     */
    constructor($$source = {}) {
        if (!("port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["port"] = 0;
        }
        if (!("open" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["open"] = false;
        }
        if (!("latencyMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["latencyMs"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["banner"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PortStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PortStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PortStatus(/** @type {Partial<PortStatus>} */($$parsedSource));
    }
}

/**
 * ProcessInfo is a single row of the remote process table. We use the same
 * shape for all platforms even though we currently only parse Linux ps output;
 * adding macOS/BSD parsing later just fills these same fields.
 */
export class ProcessInfo {
    /**
     * Creates a new ProcessInfo instance.
     * @param {Partial<ProcessInfo>} [$$source = {}] - The source object to create the ProcessInfo.
     */
    constructor($$source = {}) {
        if (!("pid" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["pid"] = 0;
        }
        if (!("ppid" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ppid"] = 0;
        }
        if (!("user" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["user"] = "";
        }
        if (!("cpuPct" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["cpuPct"] = 0;
        }
        if (!("memPct" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["memPct"] = 0;
        }
        if (!("rssKB" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["rssKB"] = 0;
        }
        if (!("state" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["state"] = "";
        }
        if (!("startTime" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["startTime"] = "";
        }
        if (!("command" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["command"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProcessInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProcessInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProcessInfo(/** @type {Partial<ProcessInfo>} */($$parsedSource));
    }
}

/**
 * PublicKeyView is the safe shape returned to the frontend — never the
 * private material.
 */
export class PublicKeyView {
    /**
     * Creates a new PublicKeyView instance.
     * @param {Partial<PublicKeyView>} [$$source = {}] - The source object to create the PublicKeyView.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("keyType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["keyType"] = "";
        }
        if (!("publicKey" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["publicKey"] = "";
        }
        if (!("fingerprint" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fingerprint"] = "";
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["createdAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PublicKeyView instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PublicKeyView}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PublicKeyView(/** @type {Partial<PublicKeyView>} */($$parsedSource));
    }
}

export class QueryColumn {
    /**
     * Creates a new QueryColumn instance.
     * @param {Partial<QueryColumn>} [$$source = {}] - The source object to create the QueryColumn.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QueryColumn instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {QueryColumn}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new QueryColumn(/** @type {Partial<QueryColumn>} */($$parsedSource));
    }
}

export class QueryResult {
    /**
     * Creates a new QueryResult instance.
     * @param {Partial<QueryResult>} [$$source = {}] - The source object to create the QueryResult.
     */
    constructor($$source = {}) {
        if (!("columns" in $$source)) {
            /**
             * @member
             * @type {QueryColumn[]}
             */
            this["columns"] = [];
        }
        if (!("rows" in $$source)) {
            /**
             * @member
             * @type {string[][]}
             */
            this["rows"] = [];
        }
        if (!("rowCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["rowCount"] = 0;
        }
        if (!("truncated" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["truncated"] = false;
        }
        if (!("durationMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["durationMs"] = 0;
        }
        if (!("commandTag" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["commandTag"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QueryResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {QueryResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType10;
        const $$createField1_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField0_0($$parsedSource["columns"]);
        }
        if ("rows" in $$parsedSource) {
            $$parsedSource["rows"] = $$createField1_0($$parsedSource["rows"]);
        }
        return new QueryResult(/** @type {Partial<QueryResult>} */($$parsedSource));
    }
}

export class RecordingDetail {
    /**
     * Creates a new RecordingDetail instance.
     * @param {Partial<RecordingDetail>} [$$source = {}] - The source object to create the RecordingDetail.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["hostID"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["hostName"] = undefined;
        }
        if (!("isLocal" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isLocal"] = false;
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("startedAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["startedAt"] = 0;
        }
        if (!("endedAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["endedAt"] = 0;
        }
        if (!("durationSeconds" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["durationSeconds"] = 0;
        }
        if (!("sizeBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sizeBytes"] = 0;
        }
        if (!("width" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["height"] = 0;
        }
        if (!("events" in $$source)) {
            /**
             * @member
             * @type {CastEvent[]}
             */
            this["events"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RecordingDetail instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RecordingDetail}
     */
    static createFrom($$source = {}) {
        const $$createField12_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("events" in $$parsedSource) {
            $$parsedSource["events"] = $$createField12_0($$parsedSource["events"]);
        }
        return new RecordingDetail(/** @type {Partial<RecordingDetail>} */($$parsedSource));
    }
}

export class SFTPEntry {
    /**
     * Creates a new SFTPEntry instance.
     * @param {Partial<SFTPEntry>} [$$source = {}] - The source object to create the SFTPEntry.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("isDir" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isDir"] = false;
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }
        if (!("mode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["mode"] = "";
        }
        if (!("modTime" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["modTime"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SFTPEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SFTPEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SFTPEntry(/** @type {Partial<SFTPEntry>} */($$parsedSource));
    }
}

/**
 * SSHConfigCandidate is one Host block from the user's ~/.ssh/config that
 * could be imported as a saved host. Identity file is reported for context
 * — we don't auto-import key material (that's a separate vault flow).
 */
export class SSHConfigCandidate {
    /**
     * Creates a new SSHConfigCandidate instance.
     * @param {Partial<SSHConfigCandidate>} [$$source = {}] - The source object to create the SSHConfigCandidate.
     */
    constructor($$source = {}) {
        if (!("alias" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["alias"] = "";
        }
        if (!("hostname" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hostname"] = "";
        }
        if (!("user" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["user"] = "";
        }
        if (!("port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["port"] = 0;
        }
        if (!("identityFile" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["identityFile"] = "";
        }
        if (!("proxyJump" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["proxyJump"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SSHConfigCandidate instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SSHConfigCandidate}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SSHConfigCandidate(/** @type {Partial<SSHConfigCandidate>} */($$parsedSource));
    }
}

/**
 * SSHConnectOptions is the ad-hoc connect payload — used when the user types
 * host/user/password directly in the terminal toolbar instead of picking from
 * the saved-host list.
 */
export class SSHConnectOptions {
    /**
     * Creates a new SSHConnectOptions instance.
     * @param {Partial<SSHConnectOptions>} [$$source = {}] - The source object to create the SSHConnectOptions.
     */
    constructor($$source = {}) {
        if (!("Host" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Host"] = "";
        }
        if (!("Port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Port"] = 0;
        }
        if (!("User" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["User"] = "";
        }
        if (!("AuthMethod" in $$source)) {
            /**
             * "password" | "key" | "agent"
             * @member
             * @type {string}
             */
            this["AuthMethod"] = "";
        }
        if (!("Password" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Password"] = "";
        }
        if (!("KeyID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["KeyID"] = "";
        }
        if (!("Cols" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Cols"] = 0;
        }
        if (!("Rows" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Rows"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SSHConnectOptions instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SSHConnectOptions}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SSHConnectOptions(/** @type {Partial<SSHConnectOptions>} */($$parsedSource));
    }
}

export class SSLResult {
    /**
     * Creates a new SSLResult instance.
     * @param {Partial<SSLResult>} [$$source = {}] - The source object to create the SSLResult.
     */
    constructor($$source = {}) {
        if (!("target" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["target"] = "";
        }
        if (!("handshakeOK" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["handshakeOK"] = false;
        }
        if (!("tlsVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["tlsVersion"] = "";
        }
        if (!("cipherSuite" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["cipherSuite"] = "";
        }
        if (!("cert" in $$source)) {
            /**
             * @member
             * @type {CertInfo}
             */
            this["cert"] = (new CertInfo());
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SSLResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SSLResult}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType14;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("cert" in $$parsedSource) {
            $$parsedSource["cert"] = $$createField4_0($$parsedSource["cert"]);
        }
        return new SSLResult(/** @type {Partial<SSLResult>} */($$parsedSource));
    }
}

/**
 * SavedConnection is the wire-safe view of a stored connection record.
 */
export class SavedConnection {
    /**
     * Creates a new SavedConnection instance.
     * @param {Partial<SavedConnection>} [$$source = {}] - The source object to create the SavedConnection.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (!("hostID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hostID"] = "";
        }
        if (!("hostName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hostName"] = "";
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["createdAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SavedConnection instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SavedConnection}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SavedConnection(/** @type {Partial<SavedConnection>} */($$parsedSource));
    }
}

/**
 * SearchHit ties a recording to one or more matched lines for the search UI.
 */
export class SearchHit {
    /**
     * Creates a new SearchHit instance.
     * @param {Partial<SearchHit>} [$$source = {}] - The source object to create the SearchHit.
     */
    constructor($$source = {}) {
        if (!("recording" in $$source)) {
            /**
             * @member
             * @type {store$0.Recording}
             */
            this["recording"] = (new store$0.Recording());
        }
        if (!("matches" in $$source)) {
            /**
             * @member
             * @type {recorder$0.Match[]}
             */
            this["matches"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchHit instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SearchHit}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType15;
        const $$createField1_0 = $$createType17;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("recording" in $$parsedSource) {
            $$parsedSource["recording"] = $$createField0_0($$parsedSource["recording"]);
        }
        if ("matches" in $$parsedSource) {
            $$parsedSource["matches"] = $$createField1_0($$parsedSource["matches"]);
        }
        return new SearchHit(/** @type {Partial<SearchHit>} */($$parsedSource));
    }
}

/**
 * Validate is a small helper the UI can call before saving — surfaces
 * undefined-default warnings, which a future rev could escalate to errors.
 */
export class SnippetValidation {
    /**
     * Creates a new SnippetValidation instance.
     * @param {Partial<SnippetValidation>} [$$source = {}] - The source object to create the SnippetValidation.
     */
    constructor($$source = {}) {
        if (!("variables" in $$source)) {
            /**
             * @member
             * @type {SnippetVariable[]}
             */
            this["variables"] = [];
        }
        if (!("warnings" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["warnings"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SnippetValidation instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SnippetValidation}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType19;
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("variables" in $$parsedSource) {
            $$parsedSource["variables"] = $$createField0_0($$parsedSource["variables"]);
        }
        if ("warnings" in $$parsedSource) {
            $$parsedSource["warnings"] = $$createField1_0($$parsedSource["warnings"]);
        }
        return new SnippetValidation(/** @type {Partial<SnippetValidation>} */($$parsedSource));
    }
}

/**
 * SnippetVariable describes one {{var}} or {{var|default}} placeholder found
 * in a snippet body, deduplicated, in first-occurrence order.
 */
export class SnippetVariable {
    /**
     * Creates a new SnippetVariable instance.
     * @param {Partial<SnippetVariable>} [$$source = {}] - The source object to create the SnippetVariable.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("default" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["default"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SnippetVariable instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SnippetVariable}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SnippetVariable(/** @type {Partial<SnippetVariable>} */($$parsedSource));
    }
}

/**
 * SystemdUnit is a single systemctl-listed service. ActiveState is what most
 * people mean by "is it running": active / inactive / failed.
 */
export class SystemdUnit {
    /**
     * Creates a new SystemdUnit instance.
     * @param {Partial<SystemdUnit>} [$$source = {}] - The source object to create the SystemdUnit.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("loadState" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["loadState"] = "";
        }
        if (!("activeState" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["activeState"] = "";
        }
        if (!("subState" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["subState"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SystemdUnit instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SystemdUnit}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SystemdUnit(/** @type {Partial<SystemdUnit>} */($$parsedSource));
    }
}

export class TerminalData {
    /**
     * Creates a new TerminalData instance.
     * @param {Partial<TerminalData>} [$$source = {}] - The source object to create the TerminalData.
     */
    constructor($$source = {}) {
        if (!("sessionID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sessionID"] = "";
        }
        if (!("data" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["data"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TerminalData instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TerminalData}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TerminalData(/** @type {Partial<TerminalData>} */($$parsedSource));
    }
}

export class TerminalExit {
    /**
     * Creates a new TerminalExit instance.
     * @param {Partial<TerminalExit>} [$$source = {}] - The source object to create the TerminalExit.
     */
    constructor($$source = {}) {
        if (!("sessionID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sessionID"] = "";
        }
        if (!("reason" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["reason"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TerminalExit instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TerminalExit}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TerminalExit(/** @type {Partial<TerminalExit>} */($$parsedSource));
    }
}

/**
 * VaultLockEvent is emitted when the vault auto-locks so the UI can navigate
 * back to the unlock screen even if no one was watching.
 */
export class VaultLockEvent {
    /**
     * Creates a new VaultLockEvent instance.
     * @param {Partial<VaultLockEvent>} [$$source = {}] - The source object to create the VaultLockEvent.
     */
    constructor($$source = {}) {
        if (!("reason" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["reason"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VaultLockEvent instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {VaultLockEvent}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VaultLockEvent(/** @type {Partial<VaultLockEvent>} */($$parsedSource));
    }
}

export class VaultStatus {
    /**
     * Creates a new VaultStatus instance.
     * @param {Partial<VaultStatus>} [$$source = {}] - The source object to create the VaultStatus.
     */
    constructor($$source = {}) {
        if (!("initialized" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["initialized"] = false;
        }
        if (!("unlocked" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["unlocked"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VaultStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {VaultStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VaultStatus(/** @type {Partial<VaultStatus>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = DNSAnswer.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = ExecResult.createFrom;
const $$createType4 = $Create.Map($Create.Any, $Create.Any);
const $$createType5 = HTTPHeader.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = PortStatus.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = QueryColumn.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = $Create.Array($$createType0);
const $$createType12 = CastEvent.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = CertInfo.createFrom;
const $$createType15 = store$0.Recording.createFrom;
const $$createType16 = recorder$0.Match.createFrom;
const $$createType17 = $Create.Array($$createType16);
const $$createType18 = SnippetVariable.createFrom;
const $$createType19 = $Create.Array($$createType18);
