// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * NetworkService provides built-in network diagnostics that run *through* a
 * connected SSH host — meaning they probe whatever the host can see, not just
 * what your laptop can. Some tools (ping, dns) shell out to standard remote
 * commands; others (port scan, ssl cert) use ssh.Client.Dial directly so we
 * get clean Go-side timing and don't depend on remote tool versions.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} hostID
 * @param {string} password
 * @param {string} target
 * @param {string} recordType
 * @returns {$CancellablePromise<$models.DNSResult>}
 */
export function DNSLookup(hostID, password, target, recordType) {
    return $Call.ByID(3368669060, hostID, password, target, recordType).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} hostID
 * @param {string} password
 * @param {string} target
 * @param {number} count
 * @returns {$CancellablePromise<$models.PingResult>}
 */
export function Ping(hostID, password, target, count) {
    return $Call.ByID(25732155, hostID, password, target, count).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * PortScan probes a list of TCP ports on `target`, reachable from the SSH
 * host's network. Concurrent dials capped at 32; per-port timeout 2s. We read
 * up to 256 bytes after a successful connect to grab a banner if the service
 * volunteers one (SSH, HTTP servers that send a Server header on connect, etc.).
 * @param {string} hostID
 * @param {string} password
 * @param {string} target
 * @param {number[]} ports
 * @returns {$CancellablePromise<$models.PortScanResult>}
 */
export function PortScan(hostID, password, target, ports) {
    return $Call.ByID(3058720009, hostID, password, target, ports).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * SSLCert dials target (default port 443) through the SSH host's network,
 * performs a TLS handshake, and returns the leaf certificate plus chain.
 * We deliberately accept invalid certs (expired, name-mismatched, self-signed)
 * — the goal is to inspect what the server returns, not to verify it.
 * @param {string} hostID
 * @param {string} password
 * @param {string} target
 * @returns {$CancellablePromise<$models.SSLResult>}
 */
export function SSLCert(hostID, password, target) {
    return $Call.ByID(3420121161, hostID, password, target).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.DNSResult.createFrom;
const $$createType1 = $models.PingResult.createFrom;
const $$createType2 = $models.PortScanResult.createFrom;
const $$createType3 = $models.SSLResult.createFrom;
