// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Config(): $CancellablePromise<$models.NotifyConfig> {
    return $Call.ByID(3557478052).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Notify is the single emit path: desktop toast (best-effort), in-app toast
 * (always), webhook POST (if configured). All three branches are independent
 * so a webhook failure doesn't suppress the toast.
 */
export function Notify(n: $models.Notification): $CancellablePromise<void> {
    return $Call.ByID(2726372343, n);
}

/**
 * NotifyDebounced is the rule-trigger entry point. `key` identifies an alert
 * dimension (e.g. "metrics:cpu:host_abc") so a sustained breach fires once
 * per debounce window instead of once per poll.
 */
export function NotifyDebounced(key: string, n: $models.Notification): $CancellablePromise<void> {
    return $Call.ByID(360550024, key, n);
}

/**
 * SetDesktopEnabled / SetWebhookURL are wrapper setters the frontend uses
 * from the Settings panel.
 */
export function SetDesktopEnabled(on: boolean): $CancellablePromise<void> {
    return $Call.ByID(2007286951, on);
}

export function SetLongExecSeconds(seconds: number): $CancellablePromise<void> {
    return $Call.ByID(2095174402, seconds);
}

export function SetWebhookURL(url: string): $CancellablePromise<void> {
    return $Call.ByID(1881875804, url);
}

/**
 * Test fires a single notification — exposed to the frontend so the user can
 * verify their settings without waiting for a real event.
 */
export function Test(): $CancellablePromise<void> {
    return $Call.ByID(1245362410);
}

// Private type creation functions
const $$createType0 = $models.NotifyConfig.createFrom;
