// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<$models.NotifyConfig>}
 */
export function Config() {
    return $Call.ByID(3557478052).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Notify is the single emit path: desktop toast (best-effort), in-app toast
 * (always), webhook POST (if configured). All three branches are independent
 * so a webhook failure doesn't suppress the toast.
 * @param {$models.Notification} n
 * @returns {$CancellablePromise<void>}
 */
export function Notify(n) {
    return $Call.ByID(2726372343, n);
}

/**
 * NotifyDebounced is the rule-trigger entry point. `key` identifies an alert
 * dimension (e.g. "metrics:cpu:host_abc") so a sustained breach fires once
 * per debounce window instead of once per poll.
 * @param {string} key
 * @param {$models.Notification} n
 * @returns {$CancellablePromise<void>}
 */
export function NotifyDebounced(key, n) {
    return $Call.ByID(360550024, key, n);
}

/**
 * SetDesktopEnabled / SetWebhookURL are wrapper setters the frontend uses
 * from the Settings panel.
 * @param {boolean} on
 * @returns {$CancellablePromise<void>}
 */
export function SetDesktopEnabled(on) {
    return $Call.ByID(2007286951, on);
}

/**
 * @param {number} seconds
 * @returns {$CancellablePromise<void>}
 */
export function SetLongExecSeconds(seconds) {
    return $Call.ByID(2095174402, seconds);
}

/**
 * @param {string} url
 * @returns {$CancellablePromise<void>}
 */
export function SetWebhookURL(url) {
    return $Call.ByID(1881875804, url);
}

/**
 * Test fires a single notification — exposed to the frontend so the user can
 * verify their settings without waiting for a real event.
 * @returns {$CancellablePromise<void>}
 */
export function Test() {
    return $Call.ByID(1245362410);
}

// Private type creation functions
const $$createType0 = $models.NotifyConfig.createFrom;
