// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PluginService exposes plugin discovery and lifecycle to the frontend.
 * It does NOT load plugins automatically at construction time — the user
 * has to opt in from the Plugins panel — to avoid running unsigned third-
 * party code at startup of a fresh install.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as plugin$0 from "./internal/plugin/models.js";

/**
 * HostNotify is the host-RPC backchannel surfaced to plugin iframes:
 * they postMessage `{type: "host.notify", title, body}` to the parent
 * window, the workspace bridge calls this method, and we route it
 * through the existing NotificationService. Routed methods are an
 * allowlist — anything else gets dropped, matching the Permissions
 * model from the manifest.
 */
export function HostNotify(pluginID: string, title: string, body: string): $CancellablePromise<void> {
    return $Call.ByID(3259703193, pluginID, title, body);
}

export function List(): $CancellablePromise<plugin$0.PluginInfo[]> {
    return $Call.ByID(2357850258).then(($result: any) => {
        return $$createType1($result);
    });
}

export function LoadAll(): $CancellablePromise<plugin$0.PluginInfo[]> {
    return $Call.ByID(3040512005).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Panels returns the flat list of every loaded plugin's declared panels.
 * The frontend uses this to inject extra entries into the sidebar nav.
 */
export function Panels(): $CancellablePromise<plugin$0.PanelView[]> {
    return $Call.ByID(1793021253).then(($result: any) => {
        return $$createType3($result);
    });
}

export function Reload(): $CancellablePromise<plugin$0.PluginInfo[]> {
    return $Call.ByID(3198680379).then(($result: any) => {
        return $$createType1($result);
    });
}

export function Root(): $CancellablePromise<string> {
    return $Call.ByID(1810785042);
}

export function StopAll(): $CancellablePromise<void> {
    return $Call.ByID(2698224381);
}

// Private type creation functions
const $$createType0 = plugin$0.PluginInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = plugin$0.PanelView.createFrom;
const $$createType3 = $Create.Array($$createType2);
