// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PortForwardService provides local/remote/dynamic SSH tunnels persisted in
 * the DB. Each active forward holds a pooled SSH client for as long as it
 * runs, so the connection is shared with any other operation on the same host.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "./internal/store/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {store$0.Forward} f
 * @returns {$CancellablePromise<store$0.Forward>}
 */
export function Create(f) {
    return $Call.ByID(1473726765, f).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function Delete(id) {
    return $Call.ByID(2038724218, id);
}

/**
 * CRUD on the saved forwards.
 * @returns {$CancellablePromise<$models.ActiveForward[]>}
 */
export function List() {
    return $Call.ByID(2379969617).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * Start opens the listener (or remote bind), grabs an SSH client from the
 * pool, and begins accepting connections in the background. password is the
 * runtime SSH password for password-auth hosts (transient).
 * @param {string} forwardID
 * @param {string} password
 * @returns {$CancellablePromise<void>}
 */
export function Start(forwardID, password) {
    return $Call.ByID(961841807, forwardID, password);
}

/**
 * @param {string} forwardID
 * @returns {$CancellablePromise<void>}
 */
export function Stop(forwardID) {
    return $Call.ByID(792424277, forwardID);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function StopAll() {
    return $Call.ByID(738273236);
}

// Private type creation functions
const $$createType0 = store$0.Forward.createFrom;
const $$createType1 = $models.ActiveForward.createFrom;
const $$createType2 = $Create.Array($$createType1);
