// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Kill sends `signal` to `pid`. Signal must be one of TERM/HUP/KILL/INT to
 * keep the surface small and obvious. With useSudo=true we shell into sudo,
 * which requires passwordless sudo for the SSH user — otherwise it'll hang
 * waiting for a password we have no way to provide here.
 * @param {string} hostID
 * @param {string} password
 * @param {number} pid
 * @param {string} signal
 * @param {boolean} useSudo
 * @returns {$CancellablePromise<void>}
 */
export function Kill(hostID, password, pid, signal, useSudo) {
    return $Call.ByID(1374212436, hostID, password, pid, signal, useSudo);
}

/**
 * ServiceAction runs systemctl <action> <unit>. With useSudo we go through
 * sudo -n; without, only the user's own user-units will respond.
 * @param {string} hostID
 * @param {string} password
 * @param {string} unit
 * @param {string} action
 * @param {boolean} useSudo
 * @returns {$CancellablePromise<string>}
 */
export function ServiceAction(hostID, password, unit, action, useSudo) {
    return $Call.ByID(3162536045, hostID, password, unit, action, useSudo);
}

/**
 * Services lists systemd services. Returns empty slice (not error) on hosts
 * without systemctl so the UI can render "no service manager" cleanly.
 * @param {string} hostID
 * @param {string} password
 * @returns {$CancellablePromise<$models.SystemdUnit[]>}
 */
export function Services(hostID, password) {
    return $Call.ByID(1682478316, hostID, password).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * Top returns the top N processes by CPU. The remote command is portable
 * across most Linux distributions (uses ps with explicit field selection).
 * Caller can re-sort client-side; we always return CPU-desc to keep the
 * "kill the runaway" flow one click away.
 * @param {string} hostID
 * @param {string} password
 * @param {number} limit
 * @returns {$CancellablePromise<$models.ProcessInfo[]>}
 */
export function Top(hostID, password, limit) {
    return $Call.ByID(3485414823, hostID, password, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.SystemdUnit.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.ProcessInfo.createFrom;
const $$createType3 = $Create.Array($$createType2);
