// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "./internal/store/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Delete(id: string): $CancellablePromise<void> {
    return $Call.ByID(85860613, id);
}

/**
 * ExportPath returns the on-disk path so the frontend can hand it to the OS
 * "reveal in folder" / save-as flow. We expose the path rather than the
 * bytes so a multi-MB export doesn't traverse the JSON bridge.
 */
export function ExportPath(id: string): $CancellablePromise<string> {
    return $Call.ByID(291778319, id);
}

export function Get(id: string): $CancellablePromise<$models.RecordingDetail> {
    return $Call.ByID(4157816598, id).then(($result: any) => {
        return $$createType0($result);
    });
}

export function IsEnabled(): $CancellablePromise<boolean> {
    return $Call.ByID(3106967851);
}

export function List(): $CancellablePromise<store$0.Recording[]> {
    return $Call.ByID(1611893494).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * ReadCastFile streams the raw cast bytes for a smaller-export case (e.g.
 * SOC2 evidence bundles). 50MB cap to keep the bridge sane.
 */
export function ReadCastFile(id: string): $CancellablePromise<string> {
    return $Call.ByID(919683799, id);
}

/**
 * Search greps every stored recording for the substring (case-insensitive)
 * and returns hits grouped per recording. Bounded at maxHitsPerRecording per
 * recording so a noisy match doesn't blow up the response.
 */
export function Search(query: string): $CancellablePromise<$models.SearchHit[]> {
    return $Call.ByID(1621142962, query).then(($result: any) => {
        return $$createType4($result);
    });
}

export function SetEnabled(on: boolean): $CancellablePromise<void> {
    return $Call.ByID(589372567, on);
}

// Private type creation functions
const $$createType0 = $models.RecordingDetail.createFrom;
const $$createType1 = store$0.Recording.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $models.SearchHit.createFrom;
const $$createType4 = $Create.Array($$createType3);
