// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "./internal/store/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function Delete(id) {
    return $Call.ByID(85860613, id);
}

/**
 * ExportPath returns the on-disk path so the frontend can hand it to the OS
 * "reveal in folder" / save-as flow. We expose the path rather than the
 * bytes so a multi-MB export doesn't traverse the JSON bridge.
 * @param {string} id
 * @returns {$CancellablePromise<string>}
 */
export function ExportPath(id) {
    return $Call.ByID(291778319, id);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<$models.RecordingDetail>}
 */
export function Get(id) {
    return $Call.ByID(4157816598, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function IsEnabled() {
    return $Call.ByID(3106967851);
}

/**
 * @returns {$CancellablePromise<store$0.Recording[]>}
 */
export function List() {
    return $Call.ByID(1611893494).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * ReadCastFile streams the raw cast bytes for a smaller-export case (e.g.
 * SOC2 evidence bundles). 50MB cap to keep the bridge sane.
 * @param {string} id
 * @returns {$CancellablePromise<string>}
 */
export function ReadCastFile(id) {
    return $Call.ByID(919683799, id);
}

/**
 * Search greps every stored recording for the substring (case-insensitive)
 * and returns hits grouped per recording. Bounded at maxHitsPerRecording per
 * recording so a noisy match doesn't blow up the response.
 * @param {string} query
 * @returns {$CancellablePromise<$models.SearchHit[]>}
 */
export function Search(query) {
    return $Call.ByID(1621142962, query).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @param {boolean} on
 * @returns {$CancellablePromise<void>}
 */
export function SetEnabled(on) {
    return $Call.ByID(589372567, on);
}

// Private type creation functions
const $$createType0 = $models.RecordingDetail.createFrom;
const $$createType1 = store$0.Recording.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $models.SearchHit.createFrom;
const $$createType4 = $Create.Array($$createType3);
