// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AnthropicAPIKey returns the plaintext key for use by the AI service. Lives
 * in main package only; never leaves Go.
 */
export function AnthropicAPIKey(): $CancellablePromise<string> {
    return $Call.ByID(3777378783);
}

export function Get(): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(710695688).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * SetAnthropicAPIKey seals the key with the vault and stores it. Empty key
 * clears the setting.
 */
export function SetAnthropicAPIKey(key: string): $CancellablePromise<void> {
    return $Call.ByID(778076535, key);
}

export function SetAutoLockMinutes(minutes: number): $CancellablePromise<void> {
    return $Call.ByID(5097981, minutes);
}

export function SetDefaultShellPath(path: string): $CancellablePromise<void> {
    return $Call.ByID(2536650630, path);
}

export function SetMetricsInterval(seconds: number): $CancellablePromise<void> {
    return $Call.ByID(1551003316, seconds);
}

export function SetTheme(theme: string): $CancellablePromise<void> {
    return $Call.ByID(466396097, theme);
}

// Private type creation functions
const $$createType0 = $models.AppSettings.createFrom;
