// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AnthropicAPIKey returns the plaintext key for use by the AI service. Lives
 * in main package only; never leaves Go.
 * @returns {$CancellablePromise<string>}
 */
export function AnthropicAPIKey() {
    return $Call.ByID(3777378783);
}

/**
 * @returns {$CancellablePromise<$models.AppSettings>}
 */
export function Get() {
    return $Call.ByID(710695688).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * SetAnthropicAPIKey seals the key with the vault and stores it. Empty key
 * clears the setting.
 * @param {string} key
 * @returns {$CancellablePromise<void>}
 */
export function SetAnthropicAPIKey(key) {
    return $Call.ByID(778076535, key);
}

/**
 * @param {number} minutes
 * @returns {$CancellablePromise<void>}
 */
export function SetAutoLockMinutes(minutes) {
    return $Call.ByID(5097981, minutes);
}

/**
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function SetDefaultShellPath(path) {
    return $Call.ByID(2536650630, path);
}

/**
 * @param {number} seconds
 * @returns {$CancellablePromise<void>}
 */
export function SetMetricsInterval(seconds) {
    return $Call.ByID(1551003316, seconds);
}

/**
 * @param {string} theme
 * @returns {$CancellablePromise<void>}
 */
export function SetTheme(theme) {
    return $Call.ByID(466396097, theme);
}

// Private type creation functions
const $$createType0 = $models.AppSettings.createFrom;
