// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Download fetches a remote file and returns it base64-encoded. Suitable for
 * the spike's small-file UI; large files will need a streaming path.
 */
export function Download(hostID: string, password: string, remotePath: string): $CancellablePromise<string> {
    return $Call.ByID(794644904, hostID, password, remotePath);
}

/**
 * List returns the entries of a remote directory. If `dir` is empty, the
 * remote home directory is used.
 */
export function List(hostID: string, password: string, dir: string): $CancellablePromise<$models.SFTPEntry[]> {
    return $Call.ByID(269609792, hostID, password, dir).then(($result: any) => {
        return $$createType1($result);
    });
}

export function Mkdir(hostID: string, password: string, dir: string): $CancellablePromise<void> {
    return $Call.ByID(1975574083, hostID, password, dir);
}

export function Remove(hostID: string, password: string, target: string): $CancellablePromise<void> {
    return $Call.ByID(1547806816, hostID, password, target);
}

/**
 * Upload writes base64-encoded payload to remoteDir/<filename>.
 */
export function Upload(hostID: string, password: string, remoteDir: string, filename: string, payloadB64: string): $CancellablePromise<void> {
    return $Call.ByID(3196629929, hostID, password, remoteDir, filename, payloadB64);
}

/**
 * WriteFile overwrites a remote file at an absolute path. Used by the
 * in-app editor — Upload (which appends a filename onto a directory) is the
 * wrong shape there. Capped at 50MB to mirror the Download cap.
 */
export function WriteFile(hostID: string, password: string, remotePath: string, payloadB64: string): $CancellablePromise<void> {
    return $Call.ByID(3545722329, hostID, password, remotePath, payloadB64);
}

// Private type creation functions
const $$createType0 = $models.SFTPEntry.createFrom;
const $$createType1 = $Create.Array($$createType0);
