// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Download fetches a remote file and returns it base64-encoded. Suitable for
 * the spike's small-file UI; large files will need a streaming path.
 * @param {string} hostID
 * @param {string} password
 * @param {string} remotePath
 * @returns {$CancellablePromise<string>}
 */
export function Download(hostID, password, remotePath) {
    return $Call.ByID(794644904, hostID, password, remotePath);
}

/**
 * List returns the entries of a remote directory. If `dir` is empty, the
 * remote home directory is used.
 * @param {string} hostID
 * @param {string} password
 * @param {string} dir
 * @returns {$CancellablePromise<$models.SFTPEntry[]>}
 */
export function List(hostID, password, dir) {
    return $Call.ByID(269609792, hostID, password, dir).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} hostID
 * @param {string} password
 * @param {string} dir
 * @returns {$CancellablePromise<void>}
 */
export function Mkdir(hostID, password, dir) {
    return $Call.ByID(1975574083, hostID, password, dir);
}

/**
 * @param {string} hostID
 * @param {string} password
 * @param {string} target
 * @returns {$CancellablePromise<void>}
 */
export function Remove(hostID, password, target) {
    return $Call.ByID(1547806816, hostID, password, target);
}

/**
 * Upload writes base64-encoded payload to remoteDir/<filename>.
 * @param {string} hostID
 * @param {string} password
 * @param {string} remoteDir
 * @param {string} filename
 * @param {string} payloadB64
 * @returns {$CancellablePromise<void>}
 */
export function Upload(hostID, password, remoteDir, filename, payloadB64) {
    return $Call.ByID(3196629929, hostID, password, remoteDir, filename, payloadB64);
}

// Private type creation functions
const $$createType0 = $models.SFTPEntry.createFrom;
const $$createType1 = $Create.Array($$createType0);
