// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Connect opens an interactive shell using ad-hoc connection params.
 */
export function Connect(sessionID: string, opts: $models.SSHConnectOptions): $CancellablePromise<void> {
    return $Call.ByID(1296524995, sessionID, opts);
}

/**
 * ConnectByHost opens an interactive shell using a saved host record. If the
 * host is configured for password auth, the runtime password is supplied via
 * the password arg (we never persist passwords).
 */
export function ConnectByHost(sessionID: string, hostID: string, password: string, cols: number, rows: number): $CancellablePromise<void> {
    return $Call.ByID(1953943528, sessionID, hostID, password, cols, rows);
}

export function Disconnect(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(2710249989, sessionID);
}

/**
 * Latency measures one round-trip via the SSH `keepalive@blacknode` request
 * and returns it in milliseconds. The remote will reject the request type
 * (we don't ship a server-side handler), but the rejection is itself a
 * round trip — that's exactly what we want to time.
 */
export function Latency(sessionID: string): $CancellablePromise<number> {
    return $Call.ByID(1637216623, sessionID);
}

export function Resize(sessionID: string, cols: number, rows: number): $CancellablePromise<void> {
    return $Call.ByID(884796119, sessionID, cols, rows);
}

export function Write(sessionID: string, data: string): $CancellablePromise<void> {
    return $Call.ByID(1772814050, sessionID, data);
}
