// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Connect opens an interactive shell using ad-hoc connection params.
 * @param {string} sessionID
 * @param {$models.SSHConnectOptions} opts
 * @returns {$CancellablePromise<void>}
 */
export function Connect(sessionID, opts) {
    return $Call.ByID(1296524995, sessionID, opts);
}

/**
 * ConnectByHost opens an interactive shell using a saved host record. If the
 * host is configured for password auth, the runtime password is supplied via
 * the password arg (we never persist passwords).
 * @param {string} sessionID
 * @param {string} hostID
 * @param {string} password
 * @param {number} cols
 * @param {number} rows
 * @returns {$CancellablePromise<void>}
 */
export function ConnectByHost(sessionID, hostID, password, cols, rows) {
    return $Call.ByID(1953943528, sessionID, hostID, password, cols, rows);
}

/**
 * @param {string} sessionID
 * @returns {$CancellablePromise<void>}
 */
export function Disconnect(sessionID) {
    return $Call.ByID(2710249989, sessionID);
}

/**
 * Latency measures one round-trip via the SSH `keepalive@blacknode` request
 * and returns it in milliseconds. The remote will reject the request type
 * (we don't ship a server-side handler), but the rejection is itself a
 * round trip — that's exactly what we want to time.
 * @param {string} sessionID
 * @returns {$CancellablePromise<number>}
 */
export function Latency(sessionID) {
    return $Call.ByID(1637216623, sessionID);
}

/**
 * @param {string} sessionID
 * @param {number} cols
 * @param {number} rows
 * @returns {$CancellablePromise<void>}
 */
export function Resize(sessionID, cols, rows) {
    return $Call.ByID(884796119, sessionID, cols, rows);
}

/**
 * @param {string} sessionID
 * @param {string} data
 * @returns {$CancellablePromise<void>}
 */
export function Write(sessionID, data) {
    return $Call.ByID(1772814050, sessionID, data);
}
