// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SyncService bridges local state and remote encrypted storage. The
 * remote is any HTTP endpoint that accepts PUT/GET/DELETE on
 * `<endpoint>/<syncBlobName>` with optional bearer auth — this works with
 * Cloudflare R2 signed URLs, a custom backend, or any S3-compatible
 * service fronted by signed URLs. Skipping the AWS SDK keeps the binary
 * small and the API surface narrow.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "./internal/store/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {$models.SyncSettings} cfg
 * @returns {$CancellablePromise<void>}
 */
export function Configure(cfg) {
    return $Call.ByID(1118613930, cfg);
}

/**
 * PublishTeam pushes a CURATED snapshot under the team blob name. The
 * curation strips notes (often personal/sensitive), drops private auth
 * material entirely, and tags rows with a "team" group prefix so a
 * pulling client can tell shared records apart from their own.
 * 
 * Records the actor as best-effort (frontend supplies a name; falls back
 * to "anonymous"). The audit row is local — it doesn't tell other team
 * members who published; the source of truth for that is whatever
 * auth lives in front of the storage endpoint.
 * @param {string} actor
 * @returns {$CancellablePromise<$models.SyncStatus>}
 */
export function PublishTeam(actor) {
    return $Call.ByID(4218452328, actor).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Pull downloads, decrypts, and merges. Conflict policy: last-write-wins
 * on each record's UpdatedAt. Records the remote knows about that we
 * don't get inserted; ours that the remote doesn't know about are
 * preserved (we don't delete based on absence — too easy to wipe a
 * device's local-only work).
 * @returns {$CancellablePromise<$models.SyncStatus>}
 */
export function Pull() {
    return $Call.ByID(456795609).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Push collects the snapshot, encrypts it, and uploads. The vault must be
 * unlocked because we use its master key.
 * @returns {$CancellablePromise<$models.SyncStatus>}
 */
export function Push() {
    return $Call.ByID(1025410274).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.SyncStatus>}
 */
export function Status() {
    return $Call.ByID(3788943212).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * SubscribeTeam pulls and merges the team blob. Same merge policy as
 * Pull (last-write-wins on UpdatedAt) — but team rows that arrive get
 * recorded in the activity log so users have a paper trail of what's
 * landed. We don't dedupe activity entries; one pull = one row.
 * @param {string} actor
 * @returns {$CancellablePromise<$models.SyncStatus>}
 */
export function SubscribeTeam(actor) {
    return $Call.ByID(1154103447, actor).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {number} limit
 * @returns {$CancellablePromise<store$0.TeamActivity[]>}
 */
export function TeamActivity(limit) {
    return $Call.ByID(1141075658, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.SyncStatus.createFrom;
const $$createType1 = store$0.TeamActivity.createFrom;
const $$createType2 = $Create.Array($$createType1);
