// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * UpdateService probes GitHub for the latest release and reports whether
 * the running binary is older. Read-only — does NOT auto-download or
 * install; clicking "Get update" opens the release page in the system
 * browser. Auto-install would need codesigning + verification, which is
 * out of scope for the spike build.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Check fetches the latest release info from GitHub. 5-second timeout so
 * a flaky network doesn't stall the settings panel.
 * @returns {$CancellablePromise<$models.UpdateInfo>}
 */
export function Check() {
    return $Call.ByID(688929688).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function CurrentVersion() {
    return $Call.ByID(212359031);
}

// Private type creation functions
const $$createType0 = $models.UpdateInfo.createFrom;
