// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Lock(): $CancellablePromise<void> {
    return $Call.ByID(337357262);
}

export function Setup(passphrase: string): $CancellablePromise<void> {
    return $Call.ByID(3202769426, passphrase);
}

export function Status(): $CancellablePromise<$models.VaultStatus> {
    return $Call.ByID(3998809027).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Unlock(passphrase: string): $CancellablePromise<void> {
    return $Call.ByID(463265505, passphrase);
}

// Private type creation functions
const $$createType0 = $models.VaultStatus.createFrom;
