// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export enum AuthMethod {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    AuthPassword = "password",
    AuthKey = "key",
    AuthAgent = "agent",
};

/**
 * Challenge is one round of a keyboard-interactive exchange. A server may send
 * several; each carries zero or more questions, and Echos[i] reports whether
 * question i's answer should be visible as it's typed (true for "Username:",
 * false for a password or OTP).
 */
export class Challenge {
    "name": string;
    "instruction": string;
    "questions": string[];
    "echos": boolean[];

    /** Creates a new Challenge instance. */
    constructor($$source: Partial<Challenge> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("instruction" in $$source)) {
            this["instruction"] = "";
        }
        if (!("questions" in $$source)) {
            this["questions"] = [];
        }
        if (!("echos" in $$source)) {
            this["echos"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Challenge instance from a string or object.
     */
    static createFrom($$source: any = {}): Challenge {
        const $$createField2_0 = $$createType0;
        const $$createField3_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("questions" in $$parsedSource) {
            $$parsedSource["questions"] = $$createField2_0($$parsedSource["questions"]);
        }
        if ("echos" in $$parsedSource) {
            $$parsedSource["echos"] = $$createField3_0($$parsedSource["echos"]);
        }
        return new Challenge($$parsedSource as Partial<Challenge>);
    }
}

/**
 * Target is the resolved set of inputs to dial a single host. Callers either
 * fill it themselves (ad-hoc connect) or use FromHost to build it from a
 * stored Host record.
 */
export class Target {
    "Host": string;
    "Port": number;
    "User": string;
    "AuthMethod": AuthMethod;

    /**
     * HostID is the saved-host record this target came from, when there is
     * one. It lets the dialer resolve a stored password itself instead of
     * having callers carry plaintext credentials around — see authFor.
     */
    "HostID": string;

    /**
     * Password is an explicitly-supplied password, used for hosts with no
     * saved credential (the user typed it at a connect prompt). Leave it
     * empty for saved hosts: the dialer resolves the stored secret from the
     * vault, which is the path that keeps plaintext off the UI bridge.
     * password auth
     */
    "Password": string;

    /**
     * key auth → vault lookup
     */
    "KeyID": string;

    /**
     * ProxyJump references another saved host (by Name) to use as a bastion.
     * Empty = direct connect. Pool.Get resolves the chain recursively.
     */
    "ProxyJump": string;

    /**
     * ForwardAgent requests SSH agent forwarding for sessions opened on this
     * connection, so a further hop from the remote can authenticate with the
     * local agent instead of a key copied onto the intermediate host.
     */
    "ForwardAgent": boolean;

    /** Creates a new Target instance. */
    constructor($$source: Partial<Target> = {}) {
        if (!("Host" in $$source)) {
            this["Host"] = "";
        }
        if (!("Port" in $$source)) {
            this["Port"] = 0;
        }
        if (!("User" in $$source)) {
            this["User"] = "";
        }
        if (!("AuthMethod" in $$source)) {
            this["AuthMethod"] = AuthMethod.$zero;
        }
        if (!("HostID" in $$source)) {
            this["HostID"] = "";
        }
        if (!("Password" in $$source)) {
            this["Password"] = "";
        }
        if (!("KeyID" in $$source)) {
            this["KeyID"] = "";
        }
        if (!("ProxyJump" in $$source)) {
            this["ProxyJump"] = "";
        }
        if (!("ForwardAgent" in $$source)) {
            this["ForwardAgent"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Target instance from a string or object.
     */
    static createFrom($$source: any = {}): Target {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Target($$parsedSource as Partial<Target>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Array($Create.Any);
