// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as service$0 from "../../../../blacknode/blacknode/internal/service/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as store$0 from "../../../../blacknode/blacknode/internal/store/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "activity:append": store$0.Activity;
            "ai:chunk": service$0.AIChunk;
            "exec:progress": service$0.ExecProgress;
            "logs:line": service$0.LogLine;
            "metrics:update": service$0.HostMetrics;
            "notification:toast": service$0.Notification;
            "terminal:data": service$0.TerminalData;
            "terminal:exit": service$0.TerminalExit;
            "vault:locked": service$0.VaultLockEvent;
        }
    }
}
