//@ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as service$0 from "../../../../blacknode/blacknode/internal/service/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "../../../../blacknode/blacknode/internal/store/models.js";

function configure() {
    Object.freeze(Object.assign($Create.Events, {
        "activity:append": $$createType0,
        "ai:chunk": $$createType1,
        "auth:prompt": $$createType2,
        "exec:progress": $$createType3,
        "logs:line": $$createType4,
        "metrics:update": $$createType5,
        "notification:toast": $$createType6,
        "sftp:progress": $$createType7,
        "terminal:data": $$createType8,
        "terminal:exit": $$createType9,
        "vault:locked": $$createType10,
    }));
}

// Private type creation functions
const $$createType0 = store$0.Activity.createFrom;
const $$createType1 = service$0.AIChunk.createFrom;
const $$createType2 = service$0.AuthPromptRequest.createFrom;
const $$createType3 = service$0.ExecProgress.createFrom;
const $$createType4 = service$0.LogLine.createFrom;
const $$createType5 = service$0.HostMetrics.createFrom;
const $$createType6 = service$0.Notification.createFrom;
const $$createType7 = service$0.TransferProgress.createFrom;
const $$createType8 = service$0.TerminalData.createFrom;
const $$createType9 = service$0.TerminalExit.createFrom;
const $$createType10 = service$0.VaultLockEvent.createFrom;

configure();
