// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Activity is one row in the unified activity feed. Source is the
 * originating service ("vault", "exec", "sync", "plugin", …). Kind is a
 * stable, programmatic identifier ("vault.unlock", "exec.complete",
 * "plugin.failed") so filters and AI prompts can match exactly. Level is
 * "info" / "warn" / "error" — the UI renders accordingly.
 */
export class Activity {
    /**
     * Creates a new Activity instance.
     * @param {Partial<Activity>} [$$source = {}] - The source object to create the Activity.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("source" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source"] = "";
        }
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (!("level" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["level"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["body"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["hostId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["hostName"] = undefined;
        }
        if (!("at" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["at"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Activity instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Activity}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Activity(/** @type {Partial<Activity>} */($$parsedSource));
    }
}

/**
 * ActivityFilter narrows the feed. Empty fields don't constrain. Limit
 * caps at 1000 to keep the IPC payload reasonable; for a deeper history
 * the UI can page via SinceAt.
 */
export class ActivityFilter {
    /**
     * Creates a new ActivityFilter instance.
     * @param {Partial<ActivityFilter>} [$$source = {}] - The source object to create the ActivityFilter.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["sources"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["levels"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["hostId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["sinceAt"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["limit"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ActivityFilter instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ActivityFilter}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sources" in $$parsedSource) {
            $$parsedSource["sources"] = $$createField0_0($$parsedSource["sources"]);
        }
        if ("levels" in $$parsedSource) {
            $$parsedSource["levels"] = $$createField1_0($$parsedSource["levels"]);
        }
        return new ActivityFilter(/** @type {Partial<ActivityFilter>} */($$parsedSource));
    }
}

export class Forward {
    /**
     * Creates a new Forward instance.
     * @param {Partial<Forward>} [$$source = {}] - The source object to create the Forward.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("hostID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hostID"] = "";
        }
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {ForwardKind}
             */
            this["kind"] = ForwardKind.$zero;
        }
        if (!("localAddr" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["localAddr"] = "";
        }
        if (!("localPort" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["localPort"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["remoteAddr"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["remotePort"] = undefined;
        }
        if (!("autoStart" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["autoStart"] = false;
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["createdAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Forward instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Forward}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Forward(/** @type {Partial<Forward>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {string}
 */
export const ForwardKind = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    /**
     * Local listener, dial through SSH to RemoteAddr:RemotePort
     */
    ForwardLocal: "local",

    /**
     * SSH server listens on RemotePort, dial back to LocalAddr:LocalPort
     */
    ForwardRemote: "remote",

    /**
     * Local SOCKS5 proxy, dialled through SSH client
     */
    ForwardDynamic: "dynamic",
};

/**
 * HTTPRequest is a saved HTTP request template. Folder groups related requests
 * (e.g. one per service/API). HostID optionally pins the request to a saved
 * host so it always runs through the same SSH tunnel.
 */
export class HTTPRequest {
    /**
     * Creates a new HTTPRequest instance.
     * @param {Partial<HTTPRequest>} [$$source = {}] - The source object to create the HTTPRequest.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("folder" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["folder"] = "";
        }
        if (!("method" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["method"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("headers" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: string }}
             */
            this["headers"] = {};
        }
        if (!("body" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["body"] = "";
        }
        if (!("hostId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hostId"] = "";
        }
        if (!("insecure" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["insecure"] = false;
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["createdAt"] = 0;
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["updatedAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HTTPRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HTTPRequest}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("headers" in $$parsedSource) {
            $$parsedSource["headers"] = $$createField5_0($$parsedSource["headers"]);
        }
        return new HTTPRequest(/** @type {Partial<HTTPRequest>} */($$parsedSource));
    }
}

/**
 * HistoryEntry records that a command was sent at a host. Sources:
 *   - "exec"          ExecService.Run (multi-host)
 *   - "ai-translate"  AI assistant translate-and-insert
 *   - "snippet"       SnippetService.Apply
 * 
 * Status (when known): "ok" (exit 0), "fail" (non-zero), "" (unknown).
 */
export class HistoryEntry {
    /**
     * Creates a new HistoryEntry instance.
     * @param {Partial<HistoryEntry>} [$$source = {}] - The source object to create the HistoryEntry.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("command" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["command"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["hostID"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["hostName"] = undefined;
        }
        if (!("source" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["status"] = undefined;
        }
        if (!("exitCode" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["exitCode"] = 0;
        }
        if (!("executedAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["executedAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HistoryEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HistoryEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HistoryEntry(/** @type {Partial<HistoryEntry>} */($$parsedSource));
    }
}

export class Host {
    /**
     * Creates a new Host instance.
     * @param {Partial<Host>} [$$source = {}] - The source object to create the Host.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("host" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["port"] = 0;
        }
        if (!("username" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["username"] = "";
        }
        if (!("authMethod" in $$source)) {
            /**
             * "password" | "key" | "agent"
             * @member
             * @type {string}
             */
            this["authMethod"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["keyID"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["group"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * "dev" | "staging" | "production" | ""
             * @member
             * @type {string | undefined}
             */
            this["environment"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * ProxyJump references another saved host (by Name) to use as a bastion.
             * Empty = direct connect. Cycles are detected at connect time.
             * @member
             * @type {string | undefined}
             */
            this["proxyJump"] = undefined;
        }
        if (!("tags" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["tags"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["notes"] = undefined;
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["createdAt"] = 0;
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["updatedAt"] = 0;
        }
        if (!("lastConnectedAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["lastConnectedAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Host instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Host}
     */
    static createFrom($$source = {}) {
        const $$createField10_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField10_0($$parsedSource["tags"]);
        }
        return new Host(/** @type {Partial<Host>} */($$parsedSource));
    }
}

/**
 * LogQuery is a saved combination of (command, host set, filter) for the
 * LogsPanel — bookmarked tail invocations the user can recall in one click.
 */
export class LogQuery {
    /**
     * Creates a new LogQuery instance.
     * @param {Partial<LogQuery>} [$$source = {}] - The source object to create the LogQuery.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("command" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["command"] = "";
        }
        if (!("hostIDs" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["hostIDs"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["filter"] = undefined;
        }
        if (!("useRegex" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["useRegex"] = false;
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["createdAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogQuery instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LogQuery}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("hostIDs" in $$parsedSource) {
            $$parsedSource["hostIDs"] = $$createField3_0($$parsedSource["hostIDs"]);
        }
        return new LogQuery(/** @type {Partial<LogQuery>} */($$parsedSource));
    }
}

export class Recording {
    /**
     * Creates a new Recording instance.
     * @param {Partial<Recording>} [$$source = {}] - The source object to create the Recording.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["hostID"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["hostName"] = undefined;
        }
        if (!("isLocal" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isLocal"] = false;
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("startedAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["startedAt"] = 0;
        }
        if (!("endedAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["endedAt"] = 0;
        }
        if (!("durationSeconds" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["durationSeconds"] = 0;
        }
        if (!("sizeBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sizeBytes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Recording instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Recording}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Recording(/** @type {Partial<Recording>} */($$parsedSource));
    }
}

/**
 * Snippet is a saved command template. The body may contain {{var}} or
 * {{var|default}} placeholders that get substituted at apply time.
 */
export class Snippet {
    /**
     * Creates a new Snippet instance.
     * @param {Partial<Snippet>} [$$source = {}] - The source object to create the Snippet.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("body" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["body"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["description"] = undefined;
        }
        if (!("tags" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["tags"] = [];
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["createdAt"] = 0;
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["updatedAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Snippet instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Snippet}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField4_0($$parsedSource["tags"]);
        }
        return new Snippet(/** @type {Partial<Snippet>} */($$parsedSource));
    }
}

/**
 * TeamActivity is a row in the local audit log of team-snapshot
 * publishes and pulls. Kind is "publish" or "pull"; counts is a small
 * JSON map of resource→count (e.g. {"hosts":12,"snippets":4}).
 */
export class TeamActivity {
    /**
     * Creates a new TeamActivity instance.
     * @param {Partial<TeamActivity>} [$$source = {}] - The source object to create the TeamActivity.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["actor"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["summary"] = undefined;
        }
        if (!("counts" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: number }}
             */
            this["counts"] = {};
        }
        if (!("at" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["at"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TeamActivity instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TeamActivity}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("counts" in $$parsedSource) {
            $$parsedSource["counts"] = $$createField4_0($$parsedSource["counts"]);
        }
        return new TeamActivity(/** @type {Partial<TeamActivity>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
