// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Forward {
    "id": string;
    "name": string;
    "hostID": string;
    "kind": ForwardKind;
    "localAddr": string;
    "localPort": number;
    "remoteAddr"?: string;
    "remotePort"?: number;
    "autoStart": boolean;
    "createdAt": number;

    /** Creates a new Forward instance. */
    constructor($$source: Partial<Forward> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("hostID" in $$source)) {
            this["hostID"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = ForwardKind.$zero;
        }
        if (!("localAddr" in $$source)) {
            this["localAddr"] = "";
        }
        if (!("localPort" in $$source)) {
            this["localPort"] = 0;
        }
        if (!("autoStart" in $$source)) {
            this["autoStart"] = false;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Forward instance from a string or object.
     */
    static createFrom($$source: any = {}): Forward {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Forward($$parsedSource as Partial<Forward>);
    }
}

export enum ForwardKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * Local listener, dial through SSH to RemoteAddr:RemotePort
     */
    ForwardLocal = "local",

    /**
     * SSH server listens on RemotePort, dial back to LocalAddr:LocalPort
     */
    ForwardRemote = "remote",

    /**
     * Local SOCKS5 proxy, dialled through SSH client
     */
    ForwardDynamic = "dynamic",
};

/**
 * HistoryEntry records that a command was sent at a host. Sources:
 *   - "exec"          ExecService.Run (multi-host)
 *   - "ai-translate"  AI assistant translate-and-insert
 *   - "snippet"       SnippetService.Apply
 * 
 * Status (when known): "ok" (exit 0), "fail" (non-zero), "" (unknown).
 */
export class HistoryEntry {
    "id": string;
    "command": string;
    "hostID"?: string;
    "hostName"?: string;
    "source": string;
    "status"?: string;
    "exitCode": number;
    "executedAt": number;

    /** Creates a new HistoryEntry instance. */
    constructor($$source: Partial<HistoryEntry> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("command" in $$source)) {
            this["command"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("exitCode" in $$source)) {
            this["exitCode"] = 0;
        }
        if (!("executedAt" in $$source)) {
            this["executedAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HistoryEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): HistoryEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HistoryEntry($$parsedSource as Partial<HistoryEntry>);
    }
}

export class Host {
    "id": string;
    "name": string;
    "host": string;
    "port": number;
    "username": string;

    /**
     * "password" | "key" | "agent"
     */
    "authMethod": string;
    "keyID"?: string;
    "group"?: string;

    /**
     * "dev" | "staging" | "production" | ""
     */
    "environment"?: string;
    "tags": string[];
    "notes"?: string;
    "createdAt": number;
    "updatedAt": number;
    "lastConnectedAt": number;

    /** Creates a new Host instance. */
    constructor($$source: Partial<Host> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }
        if (!("authMethod" in $$source)) {
            this["authMethod"] = "";
        }
        if (!("tags" in $$source)) {
            this["tags"] = [];
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = 0;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = 0;
        }
        if (!("lastConnectedAt" in $$source)) {
            this["lastConnectedAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Host instance from a string or object.
     */
    static createFrom($$source: any = {}): Host {
        const $$createField9_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField9_0($$parsedSource["tags"]);
        }
        return new Host($$parsedSource as Partial<Host>);
    }
}

/**
 * LogQuery is a saved combination of (command, host set, filter) for the
 * LogsPanel — bookmarked tail invocations the user can recall in one click.
 */
export class LogQuery {
    "id": string;
    "name": string;
    "command": string;
    "hostIDs": string[];
    "filter"?: string;
    "useRegex": boolean;
    "createdAt": number;

    /** Creates a new LogQuery instance. */
    constructor($$source: Partial<LogQuery> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("command" in $$source)) {
            this["command"] = "";
        }
        if (!("hostIDs" in $$source)) {
            this["hostIDs"] = [];
        }
        if (!("useRegex" in $$source)) {
            this["useRegex"] = false;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogQuery instance from a string or object.
     */
    static createFrom($$source: any = {}): LogQuery {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("hostIDs" in $$parsedSource) {
            $$parsedSource["hostIDs"] = $$createField3_0($$parsedSource["hostIDs"]);
        }
        return new LogQuery($$parsedSource as Partial<LogQuery>);
    }
}

export class Recording {
    "id": string;
    "title": string;
    "hostID"?: string;
    "hostName"?: string;
    "isLocal": boolean;
    "path": string;
    "startedAt": number;
    "endedAt": number;
    "durationSeconds": number;
    "sizeBytes": number;

    /** Creates a new Recording instance. */
    constructor($$source: Partial<Recording> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("isLocal" in $$source)) {
            this["isLocal"] = false;
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("startedAt" in $$source)) {
            this["startedAt"] = 0;
        }
        if (!("endedAt" in $$source)) {
            this["endedAt"] = 0;
        }
        if (!("durationSeconds" in $$source)) {
            this["durationSeconds"] = 0;
        }
        if (!("sizeBytes" in $$source)) {
            this["sizeBytes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Recording instance from a string or object.
     */
    static createFrom($$source: any = {}): Recording {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Recording($$parsedSource as Partial<Recording>);
    }
}

/**
 * Snippet is a saved command template. The body may contain {{var}} or
 * {{var|default}} placeholders that get substituted at apply time.
 */
export class Snippet {
    "id": string;
    "name": string;
    "body": string;
    "description"?: string;
    "tags": string[];
    "createdAt": number;
    "updatedAt": number;

    /** Creates a new Snippet instance. */
    constructor($$source: Partial<Snippet> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("body" in $$source)) {
            this["body"] = "";
        }
        if (!("tags" in $$source)) {
            this["tags"] = [];
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = 0;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Snippet instance from a string or object.
     */
    static createFrom($$source: any = {}): Snippet {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField4_0($$parsedSource["tags"]);
        }
        return new Snippet($$parsedSource as Partial<Snippet>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
