// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Forward {
    /**
     * Creates a new Forward instance.
     * @param {Partial<Forward>} [$$source = {}] - The source object to create the Forward.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("hostID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hostID"] = "";
        }
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {ForwardKind}
             */
            this["kind"] = ForwardKind.$zero;
        }
        if (!("localAddr" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["localAddr"] = "";
        }
        if (!("localPort" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["localPort"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["remoteAddr"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["remotePort"] = undefined;
        }
        if (!("autoStart" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["autoStart"] = false;
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["createdAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Forward instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Forward}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Forward(/** @type {Partial<Forward>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {string}
 */
export const ForwardKind = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    /**
     * Local listener, dial through SSH to RemoteAddr:RemotePort
     */
    ForwardLocal: "local",

    /**
     * SSH server listens on RemotePort, dial back to LocalAddr:LocalPort
     */
    ForwardRemote: "remote",

    /**
     * Local SOCKS5 proxy, dialled through SSH client
     */
    ForwardDynamic: "dynamic",
};

/**
 * HistoryEntry records that a command was sent at a host. Sources:
 *   - "exec"          ExecService.Run (multi-host)
 *   - "ai-translate"  AI assistant translate-and-insert
 *   - "snippet"       SnippetService.Apply
 * 
 * Status (when known): "ok" (exit 0), "fail" (non-zero), "" (unknown).
 */
export class HistoryEntry {
    /**
     * Creates a new HistoryEntry instance.
     * @param {Partial<HistoryEntry>} [$$source = {}] - The source object to create the HistoryEntry.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("command" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["command"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["hostID"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["hostName"] = undefined;
        }
        if (!("source" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["status"] = undefined;
        }
        if (!("exitCode" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["exitCode"] = 0;
        }
        if (!("executedAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["executedAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HistoryEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HistoryEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HistoryEntry(/** @type {Partial<HistoryEntry>} */($$parsedSource));
    }
}

export class Host {
    /**
     * Creates a new Host instance.
     * @param {Partial<Host>} [$$source = {}] - The source object to create the Host.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("host" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["port"] = 0;
        }
        if (!("username" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["username"] = "";
        }
        if (!("authMethod" in $$source)) {
            /**
             * "password" | "key" | "agent"
             * @member
             * @type {string}
             */
            this["authMethod"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["keyID"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["group"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * "dev" | "staging" | "production" | ""
             * @member
             * @type {string | undefined}
             */
            this["environment"] = undefined;
        }
        if (!("tags" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["tags"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["notes"] = undefined;
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["createdAt"] = 0;
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["updatedAt"] = 0;
        }
        if (!("lastConnectedAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["lastConnectedAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Host instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Host}
     */
    static createFrom($$source = {}) {
        const $$createField9_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField9_0($$parsedSource["tags"]);
        }
        return new Host(/** @type {Partial<Host>} */($$parsedSource));
    }
}

/**
 * LogQuery is a saved combination of (command, host set, filter) for the
 * LogsPanel — bookmarked tail invocations the user can recall in one click.
 */
export class LogQuery {
    /**
     * Creates a new LogQuery instance.
     * @param {Partial<LogQuery>} [$$source = {}] - The source object to create the LogQuery.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("command" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["command"] = "";
        }
        if (!("hostIDs" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["hostIDs"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["filter"] = undefined;
        }
        if (!("useRegex" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["useRegex"] = false;
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["createdAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogQuery instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LogQuery}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("hostIDs" in $$parsedSource) {
            $$parsedSource["hostIDs"] = $$createField3_0($$parsedSource["hostIDs"]);
        }
        return new LogQuery(/** @type {Partial<LogQuery>} */($$parsedSource));
    }
}

export class Recording {
    /**
     * Creates a new Recording instance.
     * @param {Partial<Recording>} [$$source = {}] - The source object to create the Recording.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["hostID"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["hostName"] = undefined;
        }
        if (!("isLocal" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isLocal"] = false;
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("startedAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["startedAt"] = 0;
        }
        if (!("endedAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["endedAt"] = 0;
        }
        if (!("durationSeconds" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["durationSeconds"] = 0;
        }
        if (!("sizeBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sizeBytes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Recording instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Recording}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Recording(/** @type {Partial<Recording>} */($$parsedSource));
    }
}

/**
 * Snippet is a saved command template. The body may contain {{var}} or
 * {{var|default}} placeholders that get substituted at apply time.
 */
export class Snippet {
    /**
     * Creates a new Snippet instance.
     * @param {Partial<Snippet>} [$$source = {}] - The source object to create the Snippet.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("body" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["body"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["description"] = undefined;
        }
        if (!("tags" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["tags"] = [];
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["createdAt"] = 0;
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["updatedAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Snippet instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Snippet}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField4_0($$parsedSource["tags"]);
        }
        return new Snippet(/** @type {Partial<Snippet>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
