// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Forward {
    "id": string;
    "name": string;
    "hostID": string;
    "kind": ForwardKind;
    "localAddr": string;
    "localPort": number;
    "remoteAddr"?: string;
    "remotePort"?: number;
    "autoStart": boolean;
    "createdAt": number;

    /** Creates a new Forward instance. */
    constructor($$source: Partial<Forward> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("hostID" in $$source)) {
            this["hostID"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = ForwardKind.$zero;
        }
        if (!("localAddr" in $$source)) {
            this["localAddr"] = "";
        }
        if (!("localPort" in $$source)) {
            this["localPort"] = 0;
        }
        if (!("autoStart" in $$source)) {
            this["autoStart"] = false;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Forward instance from a string or object.
     */
    static createFrom($$source: any = {}): Forward {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Forward($$parsedSource as Partial<Forward>);
    }
}

export enum ForwardKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * Local listener, dial through SSH to RemoteAddr:RemotePort
     */
    ForwardLocal = "local",

    /**
     * SSH server listens on RemotePort, dial back to LocalAddr:LocalPort
     */
    ForwardRemote = "remote",

    /**
     * Local SOCKS5 proxy, dialled through SSH client
     */
    ForwardDynamic = "dynamic",
};

export class Host {
    "id": string;
    "name": string;
    "host": string;
    "port": number;
    "username": string;

    /**
     * "password" | "key" | "agent"
     */
    "authMethod": string;
    "keyID"?: string;
    "group"?: string;

    /**
     * "dev" | "staging" | "production" | ""
     */
    "environment"?: string;
    "tags": string[];
    "notes"?: string;
    "createdAt": number;
    "updatedAt": number;
    "lastConnectedAt": number;

    /** Creates a new Host instance. */
    constructor($$source: Partial<Host> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }
        if (!("authMethod" in $$source)) {
            this["authMethod"] = "";
        }
        if (!("tags" in $$source)) {
            this["tags"] = [];
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = 0;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = 0;
        }
        if (!("lastConnectedAt" in $$source)) {
            this["lastConnectedAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Host instance from a string or object.
     */
    static createFrom($$source: any = {}): Host {
        const $$createField9_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField9_0($$parsedSource["tags"]);
        }
        return new Host($$parsedSource as Partial<Host>);
    }
}

export class Recording {
    "id": string;
    "title": string;
    "hostID"?: string;
    "hostName"?: string;
    "isLocal": boolean;
    "path": string;
    "startedAt": number;
    "endedAt": number;
    "durationSeconds": number;
    "sizeBytes": number;

    /** Creates a new Recording instance. */
    constructor($$source: Partial<Recording> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("isLocal" in $$source)) {
            this["isLocal"] = false;
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("startedAt" in $$source)) {
            this["startedAt"] = 0;
        }
        if (!("endedAt" in $$source)) {
            this["endedAt"] = 0;
        }
        if (!("durationSeconds" in $$source)) {
            this["durationSeconds"] = 0;
        }
        if (!("sizeBytes" in $$source)) {
            this["sizeBytes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Recording instance from a string or object.
     */
    static createFrom($$source: any = {}): Recording {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Recording($$parsedSource as Partial<Recording>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
