// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AuthPromptService bridges sshconn.Prompter to the UI. The dialer calls it from
 * inside the SSH handshake goroutine and blocks; the frontend answers by calling
 * Submit or Cancel with the request ID it received in the event.
 * 
 * This is what makes keyboard-interactive auth possible at all: the SSH protocol
 * requires answers mid-handshake, so something has to turn a synchronous
 * callback into an asynchronous round trip to a UI.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sshconn$0 from "../sshconn/models.js";

/**
 * Cancel abandons a pending prompt, failing the handshake it belongs to.
 */
export function Cancel(id: string): $CancellablePromise<void> {
    return $Call.ByID(2473140510, id);
}

/**
 * CancelAll abandons every pending prompt. Called when the vault locks or the
 * app is shutting down, so half-finished handshakes don't linger.
 */
export function CancelAll(): $CancellablePromise<void> {
    return $Call.ByID(1414308749);
}

/**
 * KeyboardInteractive answers one round of server challenges — the path that
 * carries TOTP codes, Duo confirmations and PAM password changes.
 */
export function KeyboardInteractive(t: sshconn$0.Target, c: sshconn$0.Challenge): $CancellablePromise<string[]> {
    return $Call.ByID(1636852319, t, c).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Password asks the user for a password mid-handshake, after a stored or typed
 * one was rejected.
 */
export function Password(t: sshconn$0.Target, attempt: number): $CancellablePromise<string> {
    return $Call.ByID(323495565, t, attempt);
}

/**
 * Submit delivers the user's answers for a pending prompt. Unknown IDs are not
 * an error — the prompt may have timed out or the connection dropped while the
 * dialog was open, and surfacing that as a failure to the UI is noise.
 */
export function Submit(id: string, answers: string[]): $CancellablePromise<void> {
    return $Call.ByID(4229629516, id, answers);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
