// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AutocompleteService provides ranked command completions from local sources.
 * No remote agent or shell integration is required — all matching happens
 * against history, snippets, and a built-in command list.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Suggest returns up to `limit` ranked suggestions for the given prefix and
 * optional hostID. Pass an empty hostID to match across all hosts.
 */
export function Suggest(prefix: string, hostID: string, limit: number): $CancellablePromise<$models.Suggestion[]> {
    return $Call.ByID(1791594482, prefix, hostID, limit).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.Suggestion.createFrom;
const $$createType1 = $Create.Array($$createType0);
