// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CAService issues short-lived OpenSSH user certificates.
 * 
 * The point of a CA is to stop managing authorized_keys. A host configured with
 * a @cert-authority line trusts any certificate this CA signs, so granting
 * access becomes "issue a cert" and revoking it becomes "stop issuing" — which,
 * with a short TTL, happens on its own. That last part is why the defaults here
 * are deliberately short: a certificate that outlives the reason it was issued
 * is just a long-lived credential wearing a different hat.
 * 
 * The signing key is sealed under the vault and unsealed transiently per
 * signature. It is never returned by any method on this service.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AuthorizedCALine returns the line to add to a host's sshd_config so it trusts
 * this CA. Principals are enforced per-certificate, not here.
 */
export function AuthorizedCALine(): $CancellablePromise<string> {
    return $Call.ByID(2009823103);
}

/**
 * Delete removes the CA. Every certificate it issued stops verifying.
 */
export function Delete(): $CancellablePromise<void> {
    return $Call.ByID(308241551);
}

/**
 * Info reports whether a CA exists. It needs the vault only to derive the
 * public half — a locked vault still reports existence, so the UI can show the
 * right state without prompting for a passphrase.
 */
export function Info(): $CancellablePromise<$models.CAInfo> {
    return $Call.ByID(4191194104).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Setup generates the CA signing key and seals it under the vault. It refuses
 * to replace an existing CA — see store.CAKeys.Set.
 */
export function Setup(): $CancellablePromise<$models.CAInfo> {
    return $Call.ByID(3851387729).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * SignUserKey issues a certificate for a stored key and attaches it.
 * 
 * The attach goes through KeyService.AttachCertificate rather than writing the
 * column directly, so the "was this certificate issued for this key" check
 * there covers this path too.
 */
export function SignUserKey(req: $models.SignRequest): $CancellablePromise<$models.PublicKeyView> {
    return $Call.ByID(88643449, req).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.CAInfo.createFrom;
const $$createType1 = $models.PublicKeyView.createFrom;
