// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CloudImportService discovers instances from cloud providers so hosts do not
 * have to be typed in by hand.
 * 
 * Implemented directly against each provider's REST API rather than its SDK:
 * no new module dependencies are available here, and discovery needs one
 * read-only call per provider, which is far less code than an SDK would pull
 * in. Credentials are used for the single call and never stored — the user
 * re-enters them (or pastes a short-lived token) each time.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Discover queries the provider and returns candidates without saving any.
 */
export function Discover(creds: $models.CloudCredentials): $CancellablePromise<$models.DiscoveredHost[]> {
    return $Call.ByID(3707078637, creds).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Import saves the selected candidates. Hosts already present are skipped
 * rather than duplicated, and one failure does not abort the rest.
 */
export function Import(req: $models.ImportRequest): $CancellablePromise<$models.ImportResult> {
    return $Call.ByID(1980596903, req).then(($result: any) => {
        return $$createType2($result);
    });
}

// Private type creation functions
const $$createType0 = $models.DiscoveredHost.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.ImportResult.createFrom;
