// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * HostGroupService exposes per-group connection defaults to the frontend.
 * Hosts inherit any field they leave empty; see store.ApplyGroupDefaults for
 * the precedence rules.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "../store/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Delete drops a group's defaults. Member hosts keep their group label and
 * simply stop inheriting.
 */
export function Delete(name: string): $CancellablePromise<void> {
    return $Call.ByID(4167319460, name);
}

/**
 * EnvPrelude renders the host's environment variables — group defaults merged
 * with the host's own — as shell `export` lines to send before the startup
 * snippet. Returns "" when the host defines none.
 * 
 * This is sent to the shell as typed input rather than via the SSH env channel
 * because sshd only accepts variables listed in its AcceptEnv, which almost no
 * default configuration sets.
 */
export function EnvPrelude(hostID: string): $CancellablePromise<string> {
    return $Call.ByID(4250495155, hostID);
}

/**
 * List returns every group named by at least one host, plus any group that has
 * defaults saved but no members left, so the stale row stays deletable.
 */
export function List(): $CancellablePromise<$models.GroupSummary[]> {
    return $Call.ByID(1080455263).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Resolved returns the host as it will actually be used to connect, with group
 * defaults applied. The editor reads the raw host via HostService.Get; this is
 * for showing the user what a connection will really use.
 */
export function Resolved(hostID: string): $CancellablePromise<store$0.Host> {
    return $Call.ByID(3009056735, hostID).then(($result: any) => {
        return $$createType2($result);
    });
}

export function Save(g: store$0.HostGroup): $CancellablePromise<store$0.HostGroup> {
    return $Call.ByID(2125057026, g).then(($result: any) => {
        return $$createType3($result);
    });
}

// Private type creation functions
const $$createType0 = $models.GroupSummary.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = store$0.Host.createFrom;
const $$createType3 = store$0.HostGroup.createFrom;
