// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "../store/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ApproveHostKey permanently trusts a host's SSH key fingerprint.
 */
export function ApproveHostKey(host: string, port: number, keyType: string, pubKeyBase64: string, fingerprint: string): $CancellablePromise<void> {
    return $Call.ByID(3453783468, host, port, keyType, pubKeyBase64, fingerprint);
}

/**
 * ClearPassword forgets the saved SSH password for a host.
 */
export function ClearPassword(hostID: string): $CancellablePromise<void> {
    return $Call.ByID(14931674, hostID);
}

/**
 * ClearSudoPassword forgets the saved sudo password for a host.
 */
export function ClearSudoPassword(hostID: string): $CancellablePromise<void> {
    return $Call.ByID(3013266335, hostID);
}

export function Create(h: store$0.Host): $CancellablePromise<store$0.Host> {
    return $Call.ByID(2715760614, h).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Delete removes a host and any credentials saved against it. Leaving the
 * secrets behind would strand undeletable ciphertext keyed to an id nothing
 * references.
 */
export function Delete(id: string): $CancellablePromise<void> {
    return $Call.ByID(3372977293, id);
}

export function Get(id: string): $CancellablePromise<store$0.Host> {
    return $Call.ByID(4085256030, id).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ImportSSHConfigEntries bulk-creates Host records from a user-curated
 * subset of ScanSSHConfig results. Returns the count actually inserted.
 * 
 * Auth is heuristically defaulted: if the entry has an IdentityFile, mark
 * the host as "key" auth (the user must still link a vault key after
 * import); otherwise fall back to "agent" so existing ssh-agent setups work
 * out of the box.
 * 
 * ProxyJump auto-link: a second pass resolves each entry's ProxyJump alias
 * against the set of just-imported names plus any pre-existing saved host.
 * Resolved links are written to the host record; unresolved references are
 * left in the notes field so the user can fix them by hand.
 */
export function ImportSSHConfigEntries(entries: $models.SSHConfigCandidate[]): $CancellablePromise<number> {
    return $Call.ByID(1685433603, entries);
}

export function List(): $CancellablePromise<store$0.Host[]> {
    return $Call.ByID(4079717742).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ListKnownHosts returns every trusted host key for display in Settings.
 */
export function ListKnownHosts(): $CancellablePromise<store$0.KnownHost[]> {
    return $Call.ByID(1388369876).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * RemoveKnownHost forgets a trusted host key; the next connection re-prompts (TOFU).
 */
export function RemoveKnownHost(host: string, port: number, keyType: string): $CancellablePromise<void> {
    return $Call.ByID(2853227303, host, port, keyType);
}

/**
 * ScanSSHConfig reads ~/.ssh/config (or %USERPROFILE%\.ssh\config on Windows)
 * and returns importable Host entries. Wildcard patterns (`*`, `?`, `!`) and
 * the catch-all `*` block are skipped — they're behavioral defaults, not
 * connectable hosts.
 */
export function ScanSSHConfig(): $CancellablePromise<$models.SSHConfigCandidate[]> {
    return $Call.ByID(2959866637).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * SecretStatus reports which hosts have saved credentials, as booleans. This
 * is deliberately the only credential query the frontend can make: panels
 * need to know whether a password exists (to show a "saved" affordance and to
 * decide whether to prompt), never what it is. Unsealing happens in the
 * connect path — see sshconn.Dialer.ResolveSecret.
 */
export function SecretStatus(): $CancellablePromise<{ [_ in string]?: store$0.Status }> {
    return $Call.ByID(3482900748).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * SetFavorite toggles a host's favorite flag.
 */
export function SetFavorite(id: string, favorite: boolean): $CancellablePromise<void> {
    return $Call.ByID(2969729054, id, favorite);
}

/**
 * SetPassword encrypts and persists the SSH password for a host in the vault.
 * The plaintext password is never stored; only AES-256-GCM ciphertext.
 */
export function SetPassword(hostID: string, password: string): $CancellablePromise<void> {
    return $Call.ByID(2730291407, hostID, password);
}

/**
 * SetSudoPassword encrypts and persists the sudo/root password for a host in
 * the vault. This is separate from the SSH auth password because many hosts
 * use a different password for privilege escalation (or the same user password
 * but need it at sudo time).
 */
export function SetSudoPassword(hostID: string, password: string): $CancellablePromise<void> {
    return $Call.ByID(2206115214, hostID, password);
}

export function Update(h: store$0.Host): $CancellablePromise<void> {
    return $Call.ByID(1315152939, h);
}

// Private type creation functions
const $$createType0 = store$0.Host.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = store$0.KnownHost.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $models.SSHConfigCandidate.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = store$0.Status.createFrom;
const $$createType7 = $Create.Map($Create.Any, $$createType6);
