// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AttachCertificate validates an OpenSSH certificate, verifies it was issued
 * for this key (its embedded public key must match), and stores it. Passing an
 * empty certText detaches any existing certificate.
 * @param {string} id
 * @param {string} certText
 * @returns {$CancellablePromise<$models.PublicKeyView>}
 */
export function AttachCertificate(id, certText) {
    return $Call.ByID(329099791, id, certText).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function Delete(id) {
    return $Call.ByID(2648564158, id);
}

/**
 * Generate creates a new keypair, encrypts the private half with the unlocked
 * vault master key, and stores both halves.
 * @param {string} name
 * @param {string} keyType
 * @returns {$CancellablePromise<$models.PublicKeyView>}
 */
export function Generate(name, keyType) {
    return $Call.ByID(3932499814, name, keyType).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Import takes user-supplied PEM private key bytes (optionally passphrase-
 * protected), validates them, derives the public half, and stores everything.
 * @param {string} name
 * @param {string} privatePEM
 * @param {string} passphrase
 * @returns {$CancellablePromise<$models.PublicKeyView>}
 */
export function Import(name, privatePEM, passphrase) {
    return $Call.ByID(1276898784, name, privatePEM, passphrase).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.PublicKeyView[]>}
 */
export function List() {
    return $Call.ByID(3063579717).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.PublicKeyView.createFrom;
const $$createType1 = $Create.Array($$createType0);
