// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

export function Close(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(2222346237, sessionID);
}

/**
 * Open spawns a local shell PTY for sessionID. Cwd is optional; empty defaults
 * to the user's home directory.
 */
export function Open(sessionID: string, cols: number, rows: number): $CancellablePromise<void> {
    return $Call.ByID(1277688267, sessionID, cols, rows);
}

export function Resize(sessionID: string, cols: number, rows: number): $CancellablePromise<void> {
    return $Call.ByID(541092799, sessionID, cols, rows);
}

/**
 * SendSudoPassword writes the sudo password saved against the pseudo-host id
 * "local" into this session's PTY. Same contract as the SSH equivalent: the
 * plaintext is resolved in the backend, and false means nothing is stored.
 */
export function SendSudoPassword(sessionID: string): $CancellablePromise<boolean> {
    return $Call.ByID(3340653857, sessionID);
}

export function Write(sessionID: string, data: string): $CancellablePromise<void> {
    return $Call.ByID(3314545546, sessionID, data);
}
