// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "../store/models.js";

export function DeleteQuery(id: string): $CancellablePromise<void> {
    return $Call.ByID(934190732, id);
}

export function ListQueries(): $CancellablePromise<store$0.LogQuery[]> {
    return $Call.ByID(1393909133).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Saved-query CRUD lives on the same service the panel already binds to —
 * avoids spinning up a third service for two thin methods.
 */
export function SaveQuery(q: store$0.LogQuery): $CancellablePromise<store$0.LogQuery> {
    return $Call.ByID(981207162, q).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Start opens a session per host and runs `command` (e.g. `tail -F /var/log/syslog`),
 * streaming lines back as `logs:line` events. Idempotent — calling Start with
 * an existing streamID kills the old run first.
 */
export function Start(streamID: string, hostIDs: string[], command: string): $CancellablePromise<void> {
    return $Call.ByID(3270114617, streamID, hostIDs, command);
}

export function Stop(streamID: string): $CancellablePromise<void> {
    return $Call.ByID(750409619, streamID);
}

export function StopAll(): $CancellablePromise<void> {
    return $Call.ByID(1436804550);
}

// Private type creation functions
const $$createType0 = store$0.LogQuery.createFrom;
const $$createType1 = $Create.Array($$createType0);
