// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "../store/models.js";

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteQuery(id) {
    return $Call.ByID(934190732, id);
}

/**
 * @returns {$CancellablePromise<store$0.LogQuery[]>}
 */
export function ListQueries() {
    return $Call.ByID(1393909133).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * Saved-query CRUD lives on the same service the panel already binds to —
 * avoids spinning up a third service for two thin methods.
 * @param {store$0.LogQuery} q
 * @returns {$CancellablePromise<store$0.LogQuery>}
 */
export function SaveQuery(q) {
    return $Call.ByID(981207162, q).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Start opens a session per host and runs `command` (e.g. `tail -F /var/log/syslog`),
 * streaming lines back as `logs:line` events. Idempotent — calling Start with
 * an existing streamID kills the old run first.
 * @param {string} streamID
 * @param {string[]} hostIDs
 * @param {{ [_ in string]?: string }} passwords
 * @param {string} command
 * @returns {$CancellablePromise<void>}
 */
export function Start(streamID, hostIDs, passwords, command) {
    return $Call.ByID(3270114617, streamID, hostIDs, passwords, command);
}

/**
 * @param {string} streamID
 * @returns {$CancellablePromise<void>}
 */
export function Stop(streamID) {
    return $Call.ByID(750409619, streamID);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function StopAll() {
    return $Call.ByID(1436804550);
}

// Private type creation functions
const $$createType0 = store$0.LogQuery.createFrom;
const $$createType1 = $Create.Array($$createType0);
