// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * Start begins a polling loop for the given host. Emits "metrics:update"
 * every intervalSeconds. Idempotent — calling Start twice replaces the loop.
 * @param {string} hostID
 * @param {number} intervalSeconds
 * @returns {$CancellablePromise<void>}
 */
export function Start(hostID, intervalSeconds) {
    return $Call.ByID(2268135661, hostID, intervalSeconds);
}

/**
 * @param {string} hostID
 * @returns {$CancellablePromise<void>}
 */
export function Stop(hostID) {
    return $Call.ByID(1985082911, hostID);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function StopAll() {
    return $Call.ByID(1757633482);
}
