// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MoshService wraps the system mosh-client binary to provide Mosh
 * connections. Mosh must be installed on the client machine. The server
 * must have mosh-server installed (verified over an initial SSH hop).
 * 
 * Architecture: mosh-client is exec'd with the target host details.
 * Its stdin/stdout are piped through the existing PTY infrastructure so
 * Terminal.svelte can treat it identically to an SSH or local session.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * Available reports whether mosh-client is in the PATH. The frontend uses
 * this to show or hide "Connect via Mosh" buttons.
 */
export function Available(): $CancellablePromise<boolean> {
    return $Call.ByID(427051030);
}

/**
 * Connect starts a Mosh session to the named host. The host must be reachable
 * via SSH (Mosh bootstraps via SSH to launch mosh-server).
 * 
 * cols and rows are the initial terminal size.
 */
export function Connect(sessionID: string, hostID: string, cols: number, rows: number): $CancellablePromise<void> {
    return $Call.ByID(3266864683, sessionID, hostID, cols, rows);
}

/**
 * Disconnect tears down the Mosh session cleanly.
 */
export function Disconnect(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(860899469, sessionID);
}

/**
 * Resize updates the terminal dimensions for an active Mosh session.
 */
export function Resize(sessionID: string, cols: number, rows: number): $CancellablePromise<void> {
    return $Call.ByID(632787487, sessionID, cols, rows);
}

/**
 * Write sends data into the mosh session's PTY.
 */
export function Write(sessionID: string, data: string): $CancellablePromise<void> {
    return $Call.ByID(380789866, sessionID, data);
}
