// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PluginService exposes plugin discovery and lifecycle to the frontend.
 * It does NOT load plugins automatically at construction time — the user
 * has to opt in from the Plugins panel — to avoid running unsigned third-
 * party code at startup of a fresh install.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as plugin$0 from "../plugin/models.js";

/**
 * HostNotify is the host-RPC backchannel surfaced to plugin iframes: they
 * postMessage `{type: "host.notify", ...}` to the parent window, the
 * workspace bridge calls this method, and we route it through the existing
 * NotificationService.
 * 
 * pluginID is attested by the bridge, which resolves it from the MessageEvent
 * source against its registry of mounted panel iframes — it is not a field
 * the iframe fills in, because a panel could name any plugin it liked. We
 * still re-check it here: this method is Wails-bound, so the browser context
 * can call it directly, and the frontend check is a filter rather than a
 * boundary.
 * 
 * Denials are recorded rather than dropped. A plugin trying to use a
 * capability it never declared is either broken or probing, and both are
 * things the user should be able to see in the activity feed.
 */
export function HostNotify(pluginID: string, title: string, body: string): $CancellablePromise<void> {
    return $Call.ByID(1884334924, pluginID, title, body);
}

export function List(): $CancellablePromise<plugin$0.PluginInfo[]> {
    return $Call.ByID(3669991635).then(($result: any) => {
        return $$createType1($result);
    });
}

export function LoadAll(): $CancellablePromise<plugin$0.PluginInfo[]> {
    return $Call.ByID(2144397710).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Panels returns the flat list of every loaded plugin's declared panels.
 * The frontend uses this to inject extra entries into the sidebar nav.
 */
export function Panels(): $CancellablePromise<plugin$0.PanelView[]> {
    return $Call.ByID(2043508336).then(($result: any) => {
        return $$createType3($result);
    });
}

export function Reload(): $CancellablePromise<plugin$0.PluginInfo[]> {
    return $Call.ByID(1043858418).then(($result: any) => {
        return $$createType1($result);
    });
}

export function Root(): $CancellablePromise<string> {
    return $Call.ByID(2173695847);
}

export function StopAll(): $CancellablePromise<void> {
    return $Call.ByID(2651281366);
}

// Private type creation functions
const $$createType0 = plugin$0.PluginInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = plugin$0.PanelView.createFrom;
const $$createType3 = $Create.Array($$createType2);
