// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as recorder$0 from "../recorder/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "../store/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Cleanup(): $CancellablePromise<void> {
    return $Call.ByID(2972194539);
}

export function Delete(id: string): $CancellablePromise<void> {
    return $Call.ByID(893854882, id);
}

/**
 * ExportPath returns the on-disk path so the frontend can hand it to the OS
 * "reveal in folder" / save-as flow. We expose the path rather than the
 * bytes so a multi-MB export doesn't traverse the JSON bridge.
 */
export function ExportPath(id: string): $CancellablePromise<string> {
    return $Call.ByID(2852319308, id);
}

export function Get(id: string): $CancellablePromise<$models.RecordingDetail> {
    return $Call.ByID(353853487, id).then(($result: any) => {
        return $$createType0($result);
    });
}

export function IsEnabled(): $CancellablePromise<boolean> {
    return $Call.ByID(1975675222);
}

export function List(): $CancellablePromise<store$0.Recording[]> {
    return $Call.ByID(1822758793).then(($result: any) => {
        return $$createType2($result);
    });
}

export function Policy(): $CancellablePromise<$models.RecordingPolicy> {
    return $Call.ByID(145306727).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * ReadCastFile streams the raw cast bytes for a smaller-export case (e.g.
 * SOC2 evidence bundles). 50MB cap to keep the bridge sane.
 */
export function ReadCastFile(id: string): $CancellablePromise<string> {
    return $Call.ByID(3196137456, id);
}

/**
 * Search greps every stored recording for the substring (case-insensitive)
 * and returns hits grouped per recording. Bounded at maxHitsPerRecording per
 * recording so a noisy match doesn't blow up the response.
 */
export function Search(query: string): $CancellablePromise<$models.SearchHit[]> {
    return $Call.ByID(1725092161, query).then(($result: any) => {
        return $$createType5($result);
    });
}

export function SessionState(sessionID: string): $CancellablePromise<recorder$0.SessionState> {
    return $Call.ByID(626234160, sessionID).then(($result: any) => {
        return $$createType6($result);
    });
}

export function SetEnabled(on: boolean): $CancellablePromise<void> {
    return $Call.ByID(1284823040, on);
}

export function SetPaused(sessionID: string, paused: boolean): $CancellablePromise<void> {
    return $Call.ByID(4180518389, sessionID, paused);
}

export function SetPolicy(cfg: $models.RecordingPolicy): $CancellablePromise<void> {
    return $Call.ByID(1200296925, cfg);
}

export function Storage(): $CancellablePromise<$models.RecordingStorage> {
    return $Call.ByID(3033908366).then(($result: any) => {
        return $$createType7($result);
    });
}

// Private type creation functions
const $$createType0 = $models.RecordingDetail.createFrom;
const $$createType1 = store$0.Recording.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $models.RecordingPolicy.createFrom;
const $$createType4 = $models.SearchHit.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = recorder$0.SessionState.createFrom;
const $$createType7 = $models.RecordingStorage.createFrom;
