// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Cancel(runID: string): $CancellablePromise<void> {
    return $Call.ByID(4185329036, runID);
}

export function Delete(id: string): $CancellablePromise<void> {
    return $Call.ByID(1326628657, id);
}

export function List(): $CancellablePromise<$models.Runbook[]> {
    return $Call.ByID(3638017058).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Preview resolves the same template syntax as snippets. Values are inserted
 * literally; the UI shows every resulting command before execution.
 */
export function Preview(book: $models.Runbook, values: { [_ in string]?: string }): $CancellablePromise<$models.RunbookStep[]> {
    return $Call.ByID(4009233642, book, values).then(($result: any) => {
        return $$createType3($result);
    });
}

export function Run(runID: string, book: $models.Runbook, hostIDs: string[], values: { [_ in string]?: string }): $CancellablePromise<$models.RunbookResult[]> {
    return $Call.ByID(4275159279, runID, book, hostIDs, values).then(($result: any) => {
        return $$createType5($result);
    });
}

export function Save(book: $models.Runbook): $CancellablePromise<$models.Runbook> {
    return $Call.ByID(1615601107, book).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.Runbook.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.RunbookStep.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $models.RunbookResult.createFrom;
const $$createType5 = $Create.Array($$createType4);
