// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AnthropicAPIKey returns the plaintext key for use by the AI service. Lives
 * in main package only; never leaves Go.
 */
export function AnthropicAPIKey(): $CancellablePromise<string> {
    return $Call.ByID(3765205384);
}

export function Get(): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(3487885687).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * SetAnthropicAPIKey seals the key with the vault and stores it. Empty key
 * clears the setting.
 */
export function SetAnthropicAPIKey(key: string): $CancellablePromise<void> {
    return $Call.ByID(2583872350, key);
}

export function SetAutoLockMinutes(minutes: number): $CancellablePromise<void> {
    return $Call.ByID(3986251588, minutes);
}

export function SetDefaultShellPath(path: string): $CancellablePromise<void> {
    return $Call.ByID(3996418317, path);
}

export function SetMetricsInterval(seconds: number): $CancellablePromise<void> {
    return $Call.ByID(4142291509, seconds);
}

/**
 * SetTerminalScrollback stores the per-pane scrollback line limit.
 * 
 * Rejecting instead of clamping: the number came from a person, and a silent
 * clamp would show them a saved value they did not choose with no explanation.
 * The error names both bounds so the message is actionable on its own.
 */
export function SetTerminalScrollback(lines: number): $CancellablePromise<void> {
    return $Call.ByID(4080923549, lines);
}

export function SetTheme(theme: string): $CancellablePromise<void> {
    return $Call.ByID(2182026940, theme);
}

// Private type creation functions
const $$createType0 = $models.AppSettings.createFrom;
