// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Download fetches a remote file and returns it base64-encoded. Suitable for
 * the spike's small-file UI; large files will need a streaming path.
 * @param {string} hostID
 * @param {string} remotePath
 * @returns {$CancellablePromise<string>}
 */
export function Download(hostID, remotePath) {
    return $Call.ByID(2487137113, hostID, remotePath);
}

/**
 * List returns the entries of a remote directory. If `dir` is empty, the
 * remote home directory is used.
 * @param {string} hostID
 * @param {string} dir
 * @returns {$CancellablePromise<$models.SFTPEntry[]>}
 */
export function List(hostID, dir) {
    return $Call.ByID(353307361, hostID, dir).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} hostID
 * @param {string} dir
 * @returns {$CancellablePromise<void>}
 */
export function Mkdir(hostID, dir) {
    return $Call.ByID(790964408, hostID, dir);
}

/**
 * @param {string} hostID
 * @param {string} target
 * @returns {$CancellablePromise<void>}
 */
export function Remove(hostID, target) {
    return $Call.ByID(223589213, hostID, target);
}

/**
 * Upload writes base64-encoded payload to remoteDir/<filename>.
 * @param {string} hostID
 * @param {string} remoteDir
 * @param {string} filename
 * @param {string} payloadB64
 * @returns {$CancellablePromise<void>}
 */
export function Upload(hostID, remoteDir, filename, payloadB64) {
    return $Call.ByID(1381401788, hostID, remoteDir, filename, payloadB64);
}

/**
 * WriteFile overwrites a remote file at an absolute path. Used by the
 * in-app editor — Upload (which appends a filename onto a directory) is the
 * wrong shape there. Capped at 50MB to mirror the Download cap.
 * @param {string} hostID
 * @param {string} remotePath
 * @param {string} payloadB64
 * @returns {$CancellablePromise<void>}
 */
export function WriteFile(hostID, remotePath, payloadB64) {
    return $Call.ByID(2043285130, hostID, remotePath, payloadB64);
}

// Private type creation functions
const $$createType0 = $models.SFTPEntry.createFrom;
const $$createType1 = $Create.Array($$createType0);
