// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "../store/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Apply substitutes values into the body and (optionally) records the
 * resulting command in history. Returns the rendered command. If a variable
 * has no value provided, its default is used; if no default, an empty string
 * is substituted (intentional — the user can preview before sending).
 */
export function Apply(snippetID: string, values: { [_ in string]?: string }, hostID: string, hostName: string, recordToHistory: boolean): $CancellablePromise<string> {
    return $Call.ByID(3409945725, snippetID, values, hostID, hostName, recordToHistory);
}

export function Create(sn: store$0.Snippet): $CancellablePromise<store$0.Snippet> {
    return $Call.ByID(2104235275, sn).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Delete(id: string): $CancellablePromise<void> {
    return $Call.ByID(4244213064, id);
}

/**
 * ExtractVariables scans a snippet body and returns the unique placeholders
 * in first-occurrence order, with default values when present.
 */
export function ExtractVariables(body: string): $CancellablePromise<$models.SnippetVariable[]> {
    return $Call.ByID(3810928465, body).then(($result: any) => {
        return $$createType2($result);
    });
}

export function Get(id: string): $CancellablePromise<store$0.Snippet> {
    return $Call.ByID(3114848693, id).then(($result: any) => {
        return $$createType0($result);
    });
}

export function List(): $CancellablePromise<store$0.Snippet[]> {
    return $Call.ByID(1787257155).then(($result: any) => {
        return $$createType3($result);
    });
}

export function Update(sn: store$0.Snippet): $CancellablePromise<void> {
    return $Call.ByID(166925786, sn);
}

export function Validate(body: string): $CancellablePromise<$models.SnippetValidation> {
    return $Call.ByID(1337129493, body).then(($result: any) => {
        return $$createType4($result);
    });
}

// Private type creation functions
const $$createType0 = store$0.Snippet.createFrom;
const $$createType1 = $models.SnippetVariable.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Array($$createType0);
const $$createType4 = $models.SnippetValidation.createFrom;
