// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SyncService bridges local state and remote encrypted storage. The
 * remote is any HTTP endpoint that accepts PUT/GET/DELETE on
 * `<endpoint>/<syncBlobName>` with optional bearer auth — this works with
 * Cloudflare R2 signed URLs, a custom backend, or any S3-compatible
 * service fronted by signed URLs. Skipping the AWS SDK keeps the binary
 * small and the API surface narrow.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "../store/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AutoSync performs a push followed by a pull (full bidirectional sync)
 * and returns the resulting status. Called both manually and by the
 * background goroutine.
 */
export function AutoSync(): $CancellablePromise<$models.SyncStatus> {
    return $Call.ByID(3236348223).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Configure(cfg: $models.SyncSettings): $CancellablePromise<void> {
    return $Call.ByID(3423375457, cfg);
}

/**
 * ConflictPreview does a dry-run pull: downloads the remote snapshot,
 * decrypts it, and returns the list of records that differ from the local
 * store. Does NOT write anything locally.
 */
export function ConflictPreview(): $CancellablePromise<$models.ConflictItem[]> {
    return $Call.ByID(3759462239).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * ExportSyncKey returns the sync root key as a transferable string, creating
 * one if this device doesn't have it yet. Enter it on another device with
 * ImportSyncKey to let both read the same synced data.
 * 
 * The value is the actual encryption key: anyone holding it can decrypt every
 * blob pushed to the configured endpoint.
 */
export function ExportSyncKey(): $CancellablePromise<string> {
    return $Call.ByID(3802528569);
}

/**
 * GetAutoSyncConfig returns the current auto-sync configuration.
 */
export function GetAutoSyncConfig(): $CancellablePromise<$models.AutoSyncConfig> {
    return $Call.ByID(2099698475).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * HasSyncKey reports whether this device has a sync root key yet. Doesn't need
 * the vault unlocked, so the UI can show enrollment state on the lock screen.
 */
export function HasSyncKey(): $CancellablePromise<boolean> {
    return $Call.ByID(3061143049);
}

/**
 * ImportSyncKey adopts a sync root key exported from another device, replacing
 * whatever this device had. Blobs written under the previous key become
 * unreadable, so callers should confirm before overwriting an established key.
 */
export function ImportSyncKey(encoded: string): $CancellablePromise<void> {
    return $Call.ByID(3349976436, encoded);
}

/**
 * PublishTeam pushes a CURATED snapshot under the team blob name. The
 * curation strips notes (often personal/sensitive), drops private auth
 * material entirely, and tags rows with a "team" group prefix so a
 * pulling client can tell shared records apart from their own.
 * 
 * Records the actor as best-effort (frontend supplies a name; falls back
 * to "anonymous"). The audit row is local — it doesn't tell other team
 * members who published; the source of truth for that is whatever
 * auth lives in front of the storage endpoint.
 */
export function PublishTeam(actor: string): $CancellablePromise<$models.SyncStatus> {
    return $Call.ByID(4018984287, actor).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Pull downloads, decrypts, and merges. Conflict policy: last-write-wins
 * on each record's UpdatedAt. Records the remote knows about that we
 * don't get inserted; ours that the remote doesn't know about are
 * preserved (we don't delete based on absence — too easy to wipe a
 * device's local-only work).
 */
export function Pull(): $CancellablePromise<$models.SyncStatus> {
    return $Call.ByID(831176704).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Push collects the snapshot, encrypts it, and uploads. The vault must be
 * unlocked because we use its master key.
 */
export function Push(): $CancellablePromise<$models.SyncStatus> {
    return $Call.ByID(801417323).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * SetAutoSyncConfig persists the auto-sync config and restarts the background
 * goroutine if enabled (or stops it if disabled).
 */
export function SetAutoSyncConfig(cfg: $models.AutoSyncConfig): $CancellablePromise<void> {
    return $Call.ByID(3752120455, cfg);
}

export function Status(): $CancellablePromise<$models.SyncStatus> {
    return $Call.ByID(1401200345).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * StopAutoSync shuts down the background sync goroutine. Called on vault lock
 * or app shutdown.
 */
export function StopAutoSync(): $CancellablePromise<void> {
    return $Call.ByID(1741697719);
}

/**
 * SubscribeTeam pulls and merges the team blob. Same merge policy as
 * Pull (last-write-wins on UpdatedAt) — but team rows that arrive get
 * recorded in the activity log so users have a paper trail of what's
 * landed. We don't dedupe activity entries; one pull = one row.
 */
export function SubscribeTeam(actor: string): $CancellablePromise<$models.SyncStatus> {
    return $Call.ByID(453221168, actor).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * SyncOnUnlockIfEnabled is called by the vault service after a successful
 * unlock. It reads the stored config and triggers a bidirectional sync if
 * syncOnUnlock is enabled.
 */
export function SyncOnUnlockIfEnabled(): $CancellablePromise<void> {
    return $Call.ByID(3402501735);
}

export function TeamActivity(limit: number): $CancellablePromise<store$0.TeamActivity[]> {
    return $Call.ByID(785517331, limit).then(($result: any) => {
        return $$createType5($result);
    });
}

// Private type creation functions
const $$createType0 = $models.SyncStatus.createFrom;
const $$createType1 = $models.ConflictItem.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $models.AutoSyncConfig.createFrom;
const $$createType4 = store$0.TeamActivity.createFrom;
const $$createType5 = $Create.Array($$createType4);
