// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TelnetService provides plaintext Telnet terminal sessions. Telnet is
 * unencrypted — it is offered for legacy gear (switches, BMCs, consoles) that
 * speak nothing else. Sessions are piped through the same terminal:data /
 * terminal:exit events as SSH and local shells, so the frontend treats them
 * identically.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * Connect opens a Telnet session to the saved host. Port defaults to 23 when
 * unset (or left at the SSH default of 22, which is never a Telnet port).
 */
export function Connect(sessionID: string, hostID: string, cols: number, rows: number): $CancellablePromise<void> {
    return $Call.ByID(2442422934, sessionID, hostID, cols, rows);
}

export function Disconnect(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(840871930, sessionID);
}

/**
 * Resize records the new size and reports it via NAWS if negotiated.
 */
export function Resize(sessionID: string, cols: number, rows: number): $CancellablePromise<void> {
    return $Call.ByID(2895763992, sessionID, cols, rows);
}

/**
 * Write sends user keystrokes, escaping any literal IAC (0xFF) byte per RFC 854.
 */
export function Write(sessionID: string, data: string): $CancellablePromise<void> {
    return $Call.ByID(1078882639, sessionID, data);
}
