// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ForgetPassphrase removes the stored remember-me token.
 */
export function ForgetPassphrase(): $CancellablePromise<void> {
    return $Call.ByID(2604778051);
}

export function Lock(): $CancellablePromise<void> {
    return $Call.ByID(2499084893);
}

/**
 * SetSyncService wires the sync service after construction, avoiding a
 * circular dependency at initialization time (SyncService doesn't need
 * VaultService, so this one-way late-bind keeps main.go simple).
 */
export function SetSyncService(sync: $models.SyncService | null): $CancellablePromise<void> {
    return $Call.ByID(3865152328, sync);
}

export function Setup(passphrase: string): $CancellablePromise<void> {
    return $Call.ByID(1804077983, passphrase);
}

export function Status(): $CancellablePromise<$models.VaultStatus> {
    return $Call.ByID(1852646300).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * TryAutoUnlock checks for a stored remember-me token. If one exists and hasn't
 * expired, it decrypts the passphrase and unlocks the vault silently. Returns
 * true when the vault was successfully auto-unlocked.
 */
export function TryAutoUnlock(): $CancellablePromise<boolean> {
    return $Call.ByID(3222173244);
}

export function Unlock(passphrase: string): $CancellablePromise<void> {
    return $Call.ByID(367107486, passphrase);
}

/**
 * UnlockAndRemember unlocks the vault and, if rememberDays > 0, persists the
 * passphrase (encrypted with a random machine key) so future app launches can
 * auto-unlock without prompting.
 */
export function UnlockAndRemember(passphrase: string, rememberDays: number): $CancellablePromise<void> {
    return $Call.ByID(647994632, passphrase, rememberDays);
}

// Private type creation functions
const $$createType0 = $models.VaultStatus.createFrom;
