// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<void>}
 */
export function Lock() {
    return $Call.ByID(2499084893);
}

/**
 * @param {string} passphrase
 * @returns {$CancellablePromise<void>}
 */
export function Setup(passphrase) {
    return $Call.ByID(1804077983, passphrase);
}

/**
 * @returns {$CancellablePromise<$models.VaultStatus>}
 */
export function Status() {
    return $Call.ByID(1852646300).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} passphrase
 * @returns {$CancellablePromise<void>}
 */
export function Unlock(passphrase) {
    return $Call.ByID(367107486, passphrase);
}

// Private type creation functions
const $$createType0 = $models.VaultStatus.createFrom;
