// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function DisablePIN(): $CancellablePromise<void> {
    return $Call.ByID(4253602353);
}

/**
 * EnablePIN arms a quick re-unlock PIN for the rest of this app run. Requires
 * the vault to be unlocked already: the PIN re-opens access that was proven
 * with the passphrase, it never grants it.
 * 
 * The wrapped key is held in memory only and is gone on quit, so a short PIN
 * leaves nothing on disk to attack offline. See internal/vault/pin.go.
 */
export function EnablePIN(pin: string): $CancellablePromise<void> {
    return $Call.ByID(101035696, pin);
}

/**
 * ForgetPassphrase removes the stored remember-me token and its key file.
 */
export function ForgetPassphrase(): $CancellablePromise<void> {
    return $Call.ByID(2604778051);
}

export function Lock(): $CancellablePromise<void> {
    return $Call.ByID(2499084893);
}

export function Setup(passphrase: string): $CancellablePromise<void> {
    return $Call.ByID(1804077983, passphrase);
}

export function Status(): $CancellablePromise<$models.VaultStatus> {
    return $Call.ByID(1852646300).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * TryAutoUnlock checks for a stored remember-me token. If one exists and hasn't
 * expired, it decrypts the passphrase and unlocks the vault silently. Returns
 * true when the vault was successfully auto-unlocked.
 */
export function TryAutoUnlock(): $CancellablePromise<boolean> {
    return $Call.ByID(3222173244);
}

export function Unlock(passphrase: string): $CancellablePromise<void> {
    return $Call.ByID(367107486, passphrase);
}

/**
 * UnlockAndRemember unlocks the vault and, if rememberDays > 0, persists the
 * passphrase (encrypted with a random machine key) so future app launches can
 * auto-unlock without prompting.
 */
export function UnlockAndRemember(passphrase: string, rememberDays: number): $CancellablePromise<void> {
    return $Call.ByID(647994632, passphrase, rememberDays);
}

/**
 * UnlockWithPIN re-opens the vault from the armed PIN. Failures are recorded
 * like passphrase failures, and the underlying vault discards the PIN after
 * too many so this cannot be used to grind at the master key.
 */
export function UnlockWithPIN(pin: string): $CancellablePromise<void> {
    return $Call.ByID(2358447617, pin);
}

// Private type creation functions
const $$createType0 = $models.VaultStatus.createFrom;
