// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * PanelView is the resolved version of PanelSpec — Title/Icon as declared,
 * HTML inlined from disk so the frontend can drop it straight into a
 * sandboxed iframe via srcdoc.
 */
export class PanelView {
    "pluginId": string;
    "id": string;
    "title": string;
    "icon"?: string;
    "html": string;

    /** Creates a new PanelView instance. */
    constructor($$source: Partial<PanelView> = {}) {
        if (!("pluginId" in $$source)) {
            this["pluginId"] = "";
        }
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("html" in $$source)) {
            this["html"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PanelView instance from a string or object.
     */
    static createFrom($$source: any = {}): PanelView {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PanelView($$parsedSource as Partial<PanelView>);
    }
}

/**
 * PluginInfo is the wire shape returned to the frontend. Status is one of
 * "loaded" (running) / "failed" / "stopped".
 */
export class PluginInfo {
    "id": string;
    "name": string;
    "version": string;
    "description"?: string;
    "permissions"?: string[];
    "status": string;
    "error"?: string;
    "panels"?: PanelView[];

    /** Creates a new PluginInfo instance. */
    constructor($$source: Partial<PluginInfo> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PluginInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): PluginInfo {
        const $$createField4_0 = $$createType0;
        const $$createField7_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("permissions" in $$parsedSource) {
            $$parsedSource["permissions"] = $$createField4_0($$parsedSource["permissions"]);
        }
        if ("panels" in $$parsedSource) {
            $$parsedSource["panels"] = $$createField7_0($$parsedSource["panels"]);
        }
        return new PluginInfo($$parsedSource as Partial<PluginInfo>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = PanelView.createFrom;
const $$createType2 = $Create.Array($$createType1);
