// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * PanelView is the resolved version of PanelSpec — Title/Icon as declared,
 * HTML inlined from disk so the frontend can drop it straight into a
 * sandboxed iframe via srcdoc.
 */
export class PanelView {
    /**
     * Creates a new PanelView instance.
     * @param {Partial<PanelView>} [$$source = {}] - The source object to create the PanelView.
     */
    constructor($$source = {}) {
        if (!("pluginId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["pluginId"] = "";
        }
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["icon"] = undefined;
        }
        if (!("html" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["html"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PanelView instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PanelView}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PanelView(/** @type {Partial<PanelView>} */($$parsedSource));
    }
}

/**
 * PluginInfo is the wire shape returned to the frontend. Status is one of
 * "loaded" (running) / "failed" / "stopped".
 */
export class PluginInfo {
    /**
     * Creates a new PluginInfo instance.
     * @param {Partial<PluginInfo>} [$$source = {}] - The source object to create the PluginInfo.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["description"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["permissions"] = undefined;
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {PanelView[] | undefined}
             */
            this["panels"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PluginInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PluginInfo}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType0;
        const $$createField7_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("permissions" in $$parsedSource) {
            $$parsedSource["permissions"] = $$createField4_0($$parsedSource["permissions"]);
        }
        if ("panels" in $$parsedSource) {
            $$parsedSource["panels"] = $$createField7_0($$parsedSource["panels"]);
        }
        return new PluginInfo(/** @type {Partial<PluginInfo>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = PanelView.createFrom;
const $$createType2 = $Create.Array($$createType1);
