// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Match {
    "offset": number;
    "snippet": string;

    /** Creates a new Match instance. */
    constructor($$source: Partial<Match> = {}) {
        if (!("offset" in $$source)) {
            this["offset"] = 0;
        }
        if (!("snippet" in $$source)) {
            this["snippet"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Match instance from a string or object.
     */
    static createFrom($$source: any = {}): Match {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Match($$parsedSource as Partial<Match>);
    }
}

/**
 * SessionState reports actual capture state rather than the global preference.
 */
export class SessionState {
    "recording": boolean;
    "paused": boolean;
    "limitReached": boolean;
    "error": string;

    /** Creates a new SessionState instance. */
    constructor($$source: Partial<SessionState> = {}) {
        if (!("recording" in $$source)) {
            this["recording"] = false;
        }
        if (!("paused" in $$source)) {
            this["paused"] = false;
        }
        if (!("limitReached" in $$source)) {
            this["limitReached"] = false;
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionState instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionState {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SessionState($$parsedSource as Partial<SessionState>);
    }
}
